'use client';
import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowUpRight,Bot,Package,Sparkles} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {Product} from '@/types';
import {apiClient} from '@/lib/api-client';
import {formatCurrency} from '@/lib/currency';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {SafeProductImage} from '@/components/ui/safe-product-image';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import './products.css';

type Status='active'|'limited'|'disabled';
type Report={totalSold:number;totalRevenue:number;totalOrders:number;conversionRate:number|null;conversionNote:string;basis:string;series:Array<{date:string;units:number}>;recentOrders:Array<{_id:string;orderNumber:string;customer:string;quantity:number;amount:number;status:string}>};
export function productCategory(p:Product){const category=p.categoryId as unknown as {name?:string};return category?.name||'Uncategorized';}
export function availableUnits(p:Product){const variants=p.variants?.filter(v=>v.isActive!==false)||[];return variants.length?variants.some(v=>typeof v.stock!=='number')?null:variants.reduce((sum,v)=>sum+(v.stock||0),0):p.stock;}
function StatusLabel({status}:{status:Status}){return <span className={`product-status ${status}`}><i/>{status==='active'?'Active':status==='limited'?'Limited':'Disabled'}</span>;}

export function ProductWorkspace({products,loading,error,onAdd,onEdit,onDelete}:{products:Product[];loading:boolean;error:boolean;onAdd:()=>void;onEdit:(p:Product)=>void;onDelete:(id:string)=>void}){
 const [selected,setSelected]=useState<Product|null>(null);const [disabling,setDisabling]=useState<Product|null>(null);const [reason,setReason]=useState('Out of Stock');const client=useQueryClient();
 const selling=useMutation({mutationFn:({id,status,reason}:{id:string;status:Status;reason?:string})=>apiClient.patch<Product>(`/api/products/${id}/ai-selling`,{status,reason}),onSuccess:p=>{void client.invalidateQueries({queryKey:['products']});void client.invalidateQueries({queryKey:['product-detail',p._id]});if(selected?._id===p._id)setSelected({...selected,...p,categoryId:selected.categoryId});setDisabling(null);}});
 const change=(p:Product,status:Status)=>{selling.reset();if(status==='disabled'){setReason('Out of Stock');setDisabling(p);}else selling.mutate({id:p._id,status});};
 return <>
 <div className="product-agent-note"><span className="product-agent-icon"><Bot size={21}/></span><div><strong>Your catalog. Your AI’s selling rules.</strong><p>Keep stock accurate and decide which products your sales agent can recommend.</p></div><span className="product-note-tag"><Sparkles size={13}/> AI connected</span></div>
 {selling.isError&&!disabling&&<p role="alert" className="text-sm text-destructive mb-4">Selling status could not be updated. Check your administrator access and try again.</p>}
 {loading?<div className="product-grid" aria-label="Loading products">{[1,2,3,4,5,6].map(n=><div key={n} className="product-card h-96 animate-pulse bg-muted"/>)}</div>:error?<div className="product-empty" role="alert"><Package/><h2>Products couldn’t be loaded</h2><p>Check the connection and refresh this page.</p></div>:!products.length?<div className="product-empty"><span className="product-agent-icon"><Package size={30}/></span><h2>Your next best seller starts here</h2><p>Add a product or adjust your filters to build your AI-ready catalog.</p><Button onClick={onAdd}>Add Product</Button></div>:<div className="product-grid">{products.map(p=>{const status=p.aiSellingStatus||'active';const units=availableUnits(p);return <article key={p._id} className="product-card">
 <button className="product-cover" onClick={()=>setSelected(p)} aria-label={`View ${p.name}`}><SafeProductImage src={p.images?.[0]} alt={p.name} imageClassName="object-contain p-5"/><span className="product-cover-arrow"><ArrowUpRight size={17}/></span>{!p.isActive&&<span className="product-archived">Hidden from store</span>}</button>
 <div className="product-card-body"><p className="product-category">{productCategory(p)}</p><button className="product-name" onClick={()=>setSelected(p)}>{p.name}</button><p className="product-price">{formatCurrency(p.salePrice??p.basePrice,p.currency)}</p><div className="product-inventory"><div><span>Available Units</span><strong className={units===0?'text-rose-600':''}>{units==null?'Unknown':units.toLocaleString()}</strong></div><div><span>Total Sold</span><strong>{(p.totalSold||0).toLocaleString()} <small>units</small></strong></div></div>
 <div className="product-selling-row"><div><span className="product-small-label">AI Selling</span><StatusLabel status={status}/></div><Switch aria-label={`AI selling for ${p.name}`} checked={status!=='disabled'} disabled={selling.isPending} onCheckedChange={v=>change(p,v?'active':'disabled')}/></div><button className="product-details-button" onClick={()=>setSelected(p)}>View Details<ArrowUpRight size={15}/></button></div></article>;})}</div>}
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="product-detail-dialog"><DialogHeader><DialogTitle>Product details</DialogTitle><DialogDescription>Inventory, sales performance and your AI’s product knowledge.</DialogDescription></DialogHeader>{selected&&<ProductDetail key={selected._id} product={selected} pending={selling.isPending} onStatus={s=>change(selected,s)} onEdit={p=>{setSelected(null);onEdit(p);}} onDelete={()=>{if(confirm('Hide this product from the store? Existing orders are preserved.')){onDelete(selected._id);setSelected(null);}}}/>}</DialogContent></Dialog>
 <Dialog open={!!disabling} onOpenChange={v=>{if(!v&&!selling.isPending)setDisabling(null);}}><DialogContent><DialogHeader><DialogTitle>Turn Off AI Selling?</DialogTitle><DialogDescription>The AI agent will stop recommending this product and will not accept new orders for this product.</DialogDescription></DialogHeader><fieldset className="space-y-3 my-3"><legend className="mb-3 text-sm font-semibold">Reason</legend>{['Out of Stock','Temporarily unavailable','Discontinued'].map(r=><label key={r} className="flex gap-3 items-center rounded-xl border p-3 text-sm cursor-pointer"><input type="radio" name="disable-reason" checked={reason===r} onChange={()=>setReason(r)}/>{r}</label>)}</fieldset>{selling.isError&&<p role="alert" className="text-sm text-destructive">Could not update selling status. Please try again.</p>}<div className="flex justify-end gap-3"><Button variant="outline" disabled={selling.isPending} onClick={()=>setDisabling(null)}>Cancel</Button><Button disabled={selling.isPending} onClick={()=>disabling&&selling.mutate({id:disabling._id,status:'disabled',reason})}>{selling.isPending?'Saving…':'Turn Off'}</Button></div></DialogContent></Dialog>
 </>;
}

function ProductDetail({product,pending,onStatus,onEdit,onDelete}:{product:Product;pending:boolean;onStatus:(s:Status)=>void;onEdit:(p:Product)=>void;onDelete:()=>void}){
 const [image,setImage]=useState(0);const [period,setPeriod]=useState('daily');const [editing,setEditing]=useState(false);const [answers,setAnswers]=useState(product.aiKnowledge||[]);const client=useQueryClient();
 const detail=useQuery({queryKey:['product-detail',product._id],queryFn:()=>apiClient.get<Product>(`/api/products/${product._id}`)});const p=detail.data||product;
 const report=useQuery({queryKey:['product-sales',p._id,period],queryFn:()=>apiClient.get<Report>(`/api/products/${p._id}/sales`,{params:{period}})});
 const knowledge=useMutation({mutationFn:()=>apiClient.patch(`/api/products/${p._id}`,{aiKnowledge:answers}),onSuccess:()=>{setEditing(false);void client.invalidateQueries({queryKey:['product-detail',p._id]});void client.invalidateQueries({queryKey:['products']});}});
 const status=p.aiSellingStatus||'active';const units=availableUnits(p);
 return <div className="product-detail-content"><section className="product-overview"><div><div className="product-gallery-main"><SafeProductImage src={p.images?.[image]} alt={p.name} imageClassName="object-contain p-5"/></div>{p.images?.length>1&&<div className="product-gallery-thumbs">{p.images.map((src,i)=><button key={src+i} aria-label={`Image ${i+1}`} aria-pressed={image===i} onClick={()=>setImage(i)}><SafeProductImage src={src} alt={`${p.name} ${i+1}`}/></button>)}</div>}</div><div className="product-overview-info"><p className="product-category">{productCategory(p)}</p><h2>{p.name}</h2><p className="product-price">{formatCurrency(p.salePrice??p.basePrice,p.currency)}</p><div className="text-sm text-muted-foreground leading-relaxed"><p>{p.description?.slice(0,280)}{p.description?.length>280?'…':''}</p>{p.description?.length>280&&<details className="mt-2"><summary className="text-primary cursor-pointer text-xs font-semibold">Read full description</summary><p className="mt-3 whitespace-pre-wrap">{p.description}</p></details>}</div><div className="product-inventory"><div><span>Available Units</span><strong>{units==null?'Unknown':units.toLocaleString()}</strong></div><div><span>Inventory status</span><strong>{units==null?'Verify stock':units===0?'Out of stock':units<=(p.lowStockThreshold||5)?'Low stock':'In stock'}</strong></div></div><div className="product-control-box"><div className="flex justify-between items-center gap-3"><strong className="text-sm flex items-center gap-2"><Bot size={17}/>AI Selling</strong><StatusLabel status={status}/></div><select aria-label="AI selling status" value={status} disabled={pending} onChange={e=>onStatus(e.target.value as Status)} className="w-full mt-3 rounded-lg border bg-background p-2 text-sm"><option value="active">Active · Recommend and sell</option><option value="limited">Limited · Verify stock first</option><option value="disabled">Disabled · Stop AI selling</option></select><p>{status==='limited'?'Your AI must verify live inventory before accepting an order.':status==='disabled'?`AI selling paused. ${p.aiSellingReason||''}`:'Your AI can recommend this product and accept orders when stock is available.'}</p></div><div className="flex gap-3"><Button variant="outline" onClick={()=>onEdit(p)}>Edit Product</Button><Button variant="ghost" onClick={onDelete}>Hide from Store</Button></div></div></section>
 {!!p.variants?.length&&<section className="product-detail-section"><h3>Variants</h3><div className="product-variants">{p.variants.map(v=><div key={v.variantId}><strong>{v.name}</strong><span>{v.sku}</span><span>{formatCurrency(v.price,v.currency)} · {v.stock==null?'Stock unknown':`${v.stock} available`}{!v.isActive?' · Hidden':''}</span></div>)}</div></section>}
 <section className="product-detail-section"><div className="product-section-heading"><div><p className="product-category">PRODUCT PERFORMANCE</p><h3>Sales Report</h3></div><div className="product-periods">{['daily','weekly','monthly'].map(value=><button aria-pressed={period===value} onClick={()=>setPeriod(value)} key={value}>{value}</button>)}</div></div>{report.isLoading?<p role="status">Loading sales…</p>:report.isError?<p role="alert" className="text-destructive text-sm">Sales report is unavailable. Please try again.</p>:report.data&&<><div className="product-sales-metrics">{[['Total Sold',`${report.data.totalSold.toLocaleString()} units`],['Total Revenue',formatCurrency(report.data.totalRevenue,p.currency)],['Total Orders',report.data.totalOrders.toLocaleString()],['Conversion Rate',report.data.conversionRate==null?'Not available':`${report.data.conversionRate}%`]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="product-report-note">{report.data.basis} {report.data.conversionNote}</p><h4 className="text-sm font-semibold mt-6 mb-4">{period==='daily'?'Last 30 days':period==='weekly'?'Last 12 weeks':'Last 12 months'} · Units sold</h4>{report.data.series.length?<div className="h-56 w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={report.data.series}><defs><linearGradient id="productSalesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8b5cf6" stopOpacity={.28}/><stop offset="100%" stopColor="#8b5cf6" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}} tickLine={false} axisLine={false}/><YAxis allowDecimals={false} tick={{fontSize:11}} tickLine={false} axisLine={false}/><Tooltip/><Area type="monotone" dataKey="units" name="Units sold" stroke="#8b5cf6" strokeWidth={2} fill="url(#productSalesFill)"/></AreaChart></ResponsiveContainer></div>:<div className="product-chart-empty"><Package size={24}/><p>No completed sales in this period</p><small>Real order activity will appear here.</small></div>}<h3 className="mt-8">Recent Orders</h3><div className="product-orders">{report.data.recentOrders.length?report.data.recentOrders.map(o=><div key={o._id}><div><a href="/orders" className="font-semibold text-primary">{o.orderNumber}</a><p>{o.customer||'Customer'}</p></div><span>{o.quantity} units</span><strong>{formatCurrency(o.amount,p.currency)}</strong><span className="work-status">{o.status}</span></div>):<p className="text-sm text-muted-foreground py-4">No orders for this product yet.</p>}</div></>}</section>
 <section className="product-detail-section"><div className="product-section-heading"><div><p className="product-category">TEACH YOUR SALES AGENT</p><h3>AI Product Knowledge</h3></div><Button variant="outline" onClick={()=>{setAnswers(p.aiKnowledge||[]);setEditing(!editing);}}><Sparkles size={14} className="mr-2"/>{editing?'Cancel editing':'Update AI Knowledge'}</Button></div><p className="text-sm text-muted-foreground mb-5">Your AI uses the product description, specifications, live variants and stock, plus these approved answers. Business policies come from your knowledge base.</p>{editing?<div className="space-y-4">{answers.map((a,i)=><div key={i} className="product-knowledge-item"><label>Customer question<input maxLength={300} value={a.question} onChange={e=>setAnswers(answers.map((x,j)=>j===i?{...x,question:e.target.value}:x))}/></label><label>Approved answer<textarea maxLength={2000} value={a.answer} onChange={e=>setAnswers(answers.map((x,j)=>j===i?{...x,answer:e.target.value}:x))}/></label><button className="text-xs text-destructive" onClick={()=>setAnswers(answers.filter((_,j)=>j!==i))}>Remove answer</button></div>)}<div className="flex gap-3"><Button variant="outline" onClick={()=>setAnswers([...answers,{question:'',answer:''}])}>Add answer</Button><Button disabled={knowledge.isPending||answers.some(a=>!a.question.trim()||!a.answer.trim())} onClick={()=>knowledge.mutate()}>{knowledge.isPending?'Saving…':'Save Knowledge'}</Button></div>{knowledge.isError&&<p role="alert" className="text-destructive">Could not save knowledge. Check your access and try again.</p>}</div>:p.aiKnowledge?.length?p.aiKnowledge.map((a,i)=><div key={i} className="product-knowledge-item"><p className="product-category">Customer question</p><strong>{a.question}</strong><p className="mt-3 text-sm text-muted-foreground">{a.answer}</p></div>):<p className="text-sm p-5 rounded-xl border border-dashed text-muted-foreground">No product-specific answers yet. Add the questions customers ask most often.</p>}</section>
 </div>;
}
