import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { PackageOpen, ShoppingBag, Star } from "lucide-react";
import { getFeaturedProducts } from "@/lib/api";
import { AddToCartButton } from "@/components/add-to-cart";
import { CartIcon } from "@/components/cart-icon";
export const metadata: Metadata = { title: "Shop", description: "Browse the connected SellPilot storefront product catalog." };
export default async function ShopPage() { const products = await getFeaturedProducts(); return <main className="min-h-screen bg-[var(--page-soft)] py-16"><div className="site-container"><div className="surface-card flex flex-col justify-between gap-6 overflow-hidden p-7 sm:flex-row sm:items-end sm:p-9"><div><p className="section-kicker">Connected storefront</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] text-[var(--ink)]">Product catalog</h1><p className="mt-3 max-w-xl text-[var(--muted)]">The original commerce catalog remains available while SellPilot evolves into the operating layer around it.</p></div><div className="flex items-center gap-3 rounded-xl border border-[var(--line)] bg-[var(--surface)] px-4 py-3 text-sm font-semibold text-[var(--ink)]">View cart <CartIcon /></div></div>{products.length === 0 ? <div className="mt-12 rounded-3xl border border-dashed border-[var(--line)] bg-[var(--surface)] py-20 text-center"><PackageOpen className="mx-auto h-8 w-8 text-[var(--muted)]" /><h2 className="mt-4 font-semibold text-[var(--ink)]">No products available</h2><p className="mt-2 text-sm text-[var(--muted)]">Products added in the dashboard will appear here.</p></div> : <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{products.map(product => <Link href={`/products/${product.slug || product._id}`} key={product._id} className="group surface-card block p-4"><div className="relative aspect-square overflow-hidden rounded-xl bg-slate-100">{product.images[0] ? <Image src={product.images[0]} alt={product.name} fill className="object-cover transition duration-500 group-hover:scale-105" /> : <div className="grid h-full place-items-center text-sm text-slate-400">No image</div>}</div><div className="mt-4 flex items-center gap-1 text-xs text-[var(--muted)]"><Star className="h-3.5 w-3.5 fill-amber-400 text-amber-400" />Featured product</div><h2 className="mt-2 truncate font-semibold text-[var(--ink)]">{product.name}</h2><p className="mt-1 truncate text-xs text-[var(--muted)]">{product.description}</p><div className="mt-5 flex items-center justify-between"><span className="text-lg font-bold text-[var(--ink)]">৳{product.basePrice}</span><AddToCartButton product={product} className="grid h-9 w-9 place-items-center rounded-lg bg-blue-600 text-white transition hover:bg-blue-700"><ShoppingBag className="h-4 w-4" /><span className="sr-only">Add {product.name} to cart</span></AddToCartButton></div></Link>)}</div>}</div></main>; }
