import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { PackageOpen, ShoppingBag, Star } from "lucide-react";
import { getFeaturedProducts } from "@/lib/api";
import { AddToCartButton } from "@/components/add-to-cart";
import { CartIcon } from "@/components/cart-icon";
export const metadata: Metadata = { title: "Shop", description: "Browse the connected Digitross storefront product catalog." };
export default async function ShopPage() { const products = await getFeaturedProducts(); return <main className="min-h-screen bg-slate-50 py-16"><div className="site-container"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="section-kicker">Connected storefront</p><h1 className="mt-3 text-4xl font-semibold tracking-tight text-slate-950">Product catalog</h1><p className="mt-3 max-w-xl text-slate-600">The original commerce catalog remains available while Digitross evolves into the operating layer around it.</p></div><div className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700">View cart <CartIcon /></div></div>{products.length === 0 ? <div className="mt-12 rounded-3xl border border-dashed border-slate-300 bg-white py-20 text-center"><PackageOpen className="mx-auto h-8 w-8 text-slate-400" /><h2 className="mt-4 font-semibold text-slate-900">No products available</h2><p className="mt-2 text-sm text-slate-500">Products added in the dashboard will appear here.</p></div> : <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{products.map(product => <Link href={`/products/${product.slug || product._id}`} key={product._id} className="group surface-card block p-4"><div className="relative aspect-square overflow-hidden rounded-xl bg-slate-100">{product.images[0] ? <Image src={product.images[0]} alt={product.name} fill className="object-cover transition duration-500 group-hover:scale-105" /> : <div className="grid h-full place-items-center text-sm text-slate-400">No image</div>}</div><div className="mt-4 flex items-center gap-1 text-xs text-slate-500"><Star className="h-3.5 w-3.5 fill-amber-400 text-amber-400" />Featured product</div><h2 className="mt-2 truncate font-semibold text-slate-950">{product.name}</h2><p className="mt-1 truncate text-xs text-slate-500">{product.description}</p><div className="mt-5 flex items-center justify-between"><span className="text-lg font-bold">৳{product.basePrice}</span><AddToCartButton product={product} className="grid h-9 w-9 place-items-center rounded-lg bg-blue-600 text-white transition hover:bg-blue-700"><ShoppingBag className="h-4 w-4" /><span className="sr-only">Add {product.name} to cart</span></AddToCartButton></div></Link>)}</div>}</div></main>; }
