"use client"

import { useEffect, useMemo, useRef, useState } from "react"
import Link from "next/link"
import { useSession } from "next-auth/react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { BarChart3, Bot, Box, CheckCircle2, ChevronLeft, ChevronRight, CircleHelp, FileText, Headphones, Home, Loader2, MessageCircle, Package, Search, Send, Settings, ShoppingBag, Sparkles, UserRound, Users } from "lucide-react"
import { conversationsApi, knowledgeApi, ordersApi, productsApi } from "@/lib/api"
import type { Conversation, Message, Product } from "@/types"
import { customerFacingText } from "@/lib/assistant-response"
import { SafeProductImage } from "@/components/ui/safe-product-image"
import { TestingWorkspace } from "./testing-workspace"
import {CustomerIntelligencePanel} from '@/components/customers/customer-intelligence-panel'
import "./assistant.css"
import "./testing.css"

type Filter = "all" | "ai" | "human" | "handoff"
const rail = [[Home,"/","Overview"],[MessageCircle,"/assistant","Assistant"],[Users,"/customers","Customers"],[Box,"/products","Products"],[ShoppingBag,"/orders","Orders"],[FileText,"/knowledge","Knowledge"],[BarChart3,"/admin/analytics","Analytics"]] as const
export default function AssistantPage(){
 const {data:session}=useSession();const queryClient=useQueryClient();const [mode,setMode]=useState<"test"|"live">("test");const [selectedId,setSelectedId]=useState("");const [search,setSearch]=useState("");const [filter,setFilter]=useState<Filter>("all");const scrollRef=useRef<HTMLDivElement>(null)
 const listQuery=useQuery({queryKey:["assistant-conversations",search],queryFn:()=>conversationsApi.getAll({limit:40,search,sortBy:"updatedAt",order:"desc"})})
 const conversations=useMemo(()=>filterCustomerConversations(listQuery.data?.data||[]),[listQuery.data?.data]);const visible=useMemo(()=>conversations.filter(item=>filter==="all"||(filter==="ai"&&item.controlMode==="AI_ACTIVE")||(filter==="human"&&item.controlMode==="HUMAN_ACTIVE")||(filter==="handoff"&&item.needsHumanHandoff)),[conversations,filter])
 useEffect(()=>{if(!selectedId&&visible[0])setSelectedId(String(visible[0]._id||visible[0].conversationId))},[selectedId,visible])
 const selected=conversations.find(item=>String(item._id)===selectedId||item.conversationId===selectedId)
 const messageQuery=useQuery({queryKey:["assistant-messages",selectedId],queryFn:()=>conversationsApi.getMessages(selectedId),enabled:Boolean(selectedId),refetchInterval:15000});const messages=useMemo(()=>messageQuery.data||[],[messageQuery.data])
 const productsQuery=useQuery({queryKey:["assistant-products"],queryFn:()=>productsApi.getAll({limit:6})});const ordersQuery=useQuery({queryKey:["assistant-orders"],queryFn:()=>ordersApi.getAll({limit:8})});const knowledgeQuery=useQuery({queryKey:["assistant-knowledge"],queryFn:()=>knowledgeApi.getAll({limit:4})})
 useEffect(()=>{if(scrollRef.current)scrollRef.current.scrollTop=scrollRef.current.scrollHeight},[messages,selectedId])
 const control=useMutation({mutationFn:()=>selected?.controlMode==="HUMAN_ACTIVE"?conversationsApi.returnToAI(selectedId):conversationsApi.takeOver(selectedId),onSuccess:()=>{void queryClient.invalidateQueries({queryKey:["assistant-conversations"]});void queryClient.invalidateQueries({queryKey:["conversations"]})}})
 const customerName=selected?.customer?.name||"Customer";const matchedProducts=getMessageProducts(messages);const currentIntent=selected?.currentIntent||getMessageIntent(messages)||"general";const filters:[Filter,string][]=[["ai","AI"],["human","Team"],["handoff","Help"],["all","All"]]
 if(mode==="test")return <TestingWorkspace onOpenLive={(conversationId)=>{if(conversationId)setSelectedId(conversationId);setMode("live")}}/>
 return <div className="jolly-shell"><header className="jolly-header"><Link className="jolly-logo-cell" href="/" aria-label="SellPilot overview"><BrandMark/></Link><div className="jolly-head-main"><div className="assistant-mode-switch compact"><button onClick={()=>setMode("test")}>Test AI</button><button className="is-active">Live supervision <span>{conversations.length}</span></button></div><label className="jolly-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search conversations"/><span><kbd>⌘</kbd><kbd>K</kbd></span></label><div className="jolly-head-actions"><Link className="jolly-secondary-button" href="/products"><Package size={18}/>Products</Link><Link className="jolly-primary-button" href="/orders"><ShoppingBag size={18}/>New order</Link></div></div></header>
 <aside className="jolly-rail"><Link className="jolly-account" href="/settings/security"><span>{(session?.user?.name||"S").slice(0,1).toUpperCase()}</span></Link><nav>{rail.map(([Icon,href,label])=><Link key={href} href={href} className={href==="/assistant"?"is-active":""} aria-label={label} title={label}><Icon size={20}/></Link>)}</nav><div className="jolly-rail-bottom"><Link href="/settings/business" aria-label="Settings"><Settings size={20}/></Link><Link href="/settings/integrations" aria-label="Support"><Headphones size={20}/></Link></div></aside>
 <main className="jolly-main"><button className="jolly-banner" onClick={()=>setFilter("handoff")}><b>LIVE</b><span>SellPilot is handling {conversations.filter(c=>c.controlMode==="AI_ACTIVE").length} customer conversations</span><em>Review handoffs <ChevronRight size={16}/></em></button><section className="jolly-greeting"><h1>Hello, {session?.user?.name?.split(" ")[0]||"there"}</h1><p>How can <BrandMark small/><strong>SellPilot</strong> help you?</p></section>
 <section className="jolly-conversation-card"><header><div className="jolly-customer-avatar">{customerName.slice(0,1).toUpperCase()}<i/></div><div><h2>{selected?customerName:"Your conversation workspace"}</h2><p>{selected?`${channelName(selected.platform)} · ${formatTime(selected.updatedAt)}`:"Choose a customer thread from the right panel"}</p></div>{selected&&<span className={`jolly-state ${selected.controlMode==="AI_ACTIVE"?"ai":"human"}`}>{selected.controlMode==="AI_ACTIVE"?"AI active":"Human active"}</span>}</header><div className="jolly-chat" ref={scrollRef} role="log" aria-label="Customer conversation">{messageQuery.isLoading&&<Center icon={Loader2} title="Loading conversation…"/>}{!messageQuery.isLoading&&!selected&&<Center icon={MessageCircle} title="Select a conversation" copy="Review live customer messages and the actions SellPilot took."/>}{!messageQuery.isLoading&&selected&&!messages.length&&<Center icon={MessageCircle} title="No messages yet" copy="This thread is ready when the customer sends a message."/>}{messages.map(message=><ChatMessage key={String(message._id)} message={message}/>)}</div><footer className="jolly-composer"><div><Sparkles size={18}/><span>{selected?.controlMode==="AI_ACTIVE"?"SellPilot is responding with your catalog and business knowledge.":"Your team currently controls this conversation."}</span></div><button disabled={!selected||control.isPending} onClick={()=>control.mutate()}>{control.isPending?<Loader2 className="animate-spin" size={16}/>:selected?.controlMode==="HUMAN_ACTIVE"?<Bot size={16}/>:<UserRound size={16}/>} {selected?.controlMode==="HUMAN_ACTIVE"?"Return to AI":"Take over"}</button><Link className={!selected?"is-disabled":""} href={selected?`/conversations/${selectedId}`:"/conversations"}><Send size={16}/>Open thread</Link></footer></section>
 <section className="jolly-quick-section"><h2>Quick access</h2><div><QuickCard icon={Box} title="Matched products" href="/products" action="Open catalog" empty="Products mentioned in this conversation will appear here.">{(matchedProducts.length?matchedProducts:(productsQuery.data?.data||[]).slice(0,2)).map((product,index)=><ProductRow key={String((product as Record<string,unknown>)._id||(product as Record<string,unknown>).id||index)} product={product}/>)}</QuickCard><QuickCard icon={ShoppingBag} title="Recent orders" href="/orders" action="Manage orders" empty="Orders created from conversations will appear here.">{(ordersQuery.data?.data||[]).slice(0,2).map(order=><div className="jolly-mini-row" key={String(order._id)}><span><strong>{order.orderNumber}</strong><small>{order.status}</small></span><b>৳{Number(order.total||0).toLocaleString()}</b></div>)}</QuickCard><QuickCard icon={FileText} title="Knowledge" href="/knowledge" action="Manage knowledge" empty="Add policies and answers for accurate replies.">{(knowledgeQuery.data?.data||[]).slice(0,2).map(item=><div className="jolly-mini-row" key={String(item._id)}><span><strong>{item.title}</strong><small>{item.type}</small></span><CheckCircle2 size={16}/></div>)}</QuickCard></div></section></main>
 <aside className="jolly-context"><header><div><span>AI CONTEXT</span><h2>{selected?customerName:"Conversations"}</h2></div><Link href="/conversations"><MessageCircle size={16}/>View inbox</Link></header><div className="jolly-context-tabs"><button onClick={()=>setFilter(previousFilter(filter))}><ChevronLeft size={16}/></button>{filters.map(([value,label])=><button key={value} onClick={()=>setFilter(value)} className={filter===value?"is-active":""}><small>{label}</small><strong>{countFor(conversations,value)}</strong></button>)}<button onClick={()=>setFilter(nextFilter(filter))}><ChevronRight size={16}/></button></div>{selected&&<LiveIntelligence conversation={selected} messages={messages} products={matchedProducts} intent={currentIntent}/>}<div className="jolly-context-list">{listQuery.isLoading&&<Center icon={Loader2} title="Loading conversations…"/>}{!listQuery.isLoading&&!visible.length&&<Center icon={CircleHelp} title="No matching conversations" copy="Try a different search or filter."/>}{visible.map((item,index)=><ConversationItem key={String(item._id)} item={item} active={String(item._id)===selectedId||item.conversationId===selectedId} offset={index} onSelect={()=>setSelectedId(String(item._id||item.conversationId))}/>)}</div></aside></div>
}

function BrandMark({small=false}:{small?:boolean}){return <span className={`jolly-brand-mark ${small?"small":""}`}><Bot size={small?18:22}/></span>}
function Center({icon:Icon,title,copy}:{icon:typeof MessageCircle;title:string;copy?:string}){return <div className="jolly-center-state"><Icon className={Icon===Loader2?"animate-spin":""}/><strong>{title}</strong>{copy&&<span>{copy}</span>}</div>}
function ChatMessage({message}:{message:Message}){const customer=message.role==="user";const human=message.metadata?.source==="human";const attachment=message.attachments?.find(item=>item.type?.startsWith("image/"));const products=Array.isArray(message.metadata?.products)?message.metadata.products as Array<Record<string,unknown>>:[];return <article className={`jolly-message ${customer?"customer":"assistant"}`}><div className="jolly-message-meta"><span>{customer||human?<UserRound size={14}/>:<BrandMark small/>}{customer?"Customer":human?"Your team":"SellPilot AI"}</span><time>{formatTime(message.createdAt)}</time></div><div className="jolly-message-bubble">{attachment?.url&&<div className="jolly-message-image"><SafeProductImage src={attachment.url} alt="Customer attachment"/></div>}<p>{customer||human?message.content:customerFacingText(message.content)}</p>{products.length>0&&<div className="jolly-message-products">{products.slice(0,2).map((product,index)=><ProductRow product={product} key={String(product.id||index)}/>)}</div>}</div></article>}
function ConversationItem({item,active,offset,onSelect}:{item:Conversation;active:boolean;offset:number;onSelect:()=>void}){const name=item.customer?.name||"Customer";return <button className={`jolly-conversation-item ${active?"is-active":""}`} onClick={onSelect}><span className="jolly-time"><strong>{formatTime(item.updatedAt)}</strong><small>{formatDay(item.updatedAt)}</small></span><article style={{marginTop:offset%2?8:0}}><i className={item.needsHumanHandoff?"handoff":item.controlMode==="AI_ACTIVE"?"ai":"human"}/><div><h3>{name}</h3><p>{item.lastMessage||item.lastMessagePreview||item.summary||"Conversation ready"}</p><footer><span>{channelName(item.platform)}</span><b>{item.needsHumanHandoff?"Needs help":item.controlMode==="AI_ACTIVE"?"AI active":"Team active"}</b></footer></div></article></button>}
function QuickCard({icon:Icon,title,href,action,empty,children}:{icon:typeof Box;title:string;href:string;action:string;empty:string;children:React.ReactNode}){const hasChildren=Array.isArray(children)?children.length>0:Boolean(children);return <article className="jolly-quick-card"><Icon size={20}/><h3>{title}</h3><div>{hasChildren?children:<p>{empty}</p>}</div><Link href={href}>{action}<ChevronRight size={15}/></Link></article>}
function ProductRow({product}:{product:Product|Record<string,unknown>}){const value=product as Record<string,unknown>;const image=String(value.image||(Array.isArray(value.images)?value.images[0]:"")||"");return <div className="jolly-product-row"><span>{image?<SafeProductImage src={image} alt={String(value.name||"Product")}/>:<Package size={17}/>}</span><div><strong>{String(value.name||"Catalog product")}</strong><small>{value.price!=null?`৳${Number(value.price).toLocaleString()}`:"View inventory"}</small></div></div>}
function formatTime(value?:string){return value?new Intl.DateTimeFormat("en",{hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"Now"}function formatDay(value?:string){return value?new Intl.DateTimeFormat("en",{weekday:"short"}).format(new Date(value)):"Today"}
function channelName(value?:string){return value==="facebook"?"Messenger":value==="web-widget"?"Website":value?value.charAt(0).toUpperCase()+value.slice(1):"Connected channel"}
function getMessageIntent(messages:Message[]){for(let i=messages.length-1;i>=0;i--){const value=messages[i].metadata?.intent;if(typeof value==="string")return value}return ""}function getMessageProducts(messages:Message[]){for(let i=messages.length-1;i>=0;i--){const value=messages[i].metadata?.products;if(Array.isArray(value)&&value.length)return value as Array<Record<string,unknown>>}return []}
function countFor(items:Conversation[],filter:Filter){if(filter==="all")return items.length;if(filter==="ai")return items.filter(i=>i.controlMode==="AI_ACTIVE").length;if(filter==="human")return items.filter(i=>i.controlMode==="HUMAN_ACTIVE").length;return items.filter(i=>i.needsHumanHandoff).length}const filterOrder:Filter[]=["ai","human","handoff","all"];function previousFilter(value:Filter){return filterOrder[(filterOrder.indexOf(value)+3)%4]}function nextFilter(value:Filter){return filterOrder[(filterOrder.indexOf(value)+1)%4]}
function filterCustomerConversations(items:Conversation[]){return items.filter(item=>item.platform!=="manual"&&!item.conversationId.startsWith("test_"))}
function LiveIntelligence({conversation}:{conversation:Conversation;messages:Message[];products:Array<Record<string,unknown>>;intent:string}){return <CustomerIntelligencePanel conversationId={String(conversation._id)}/>}
