"use client"

import { FormEvent, useEffect, useMemo, useRef, useState } from "react"
import Link from "next/link"
import { useQuery } from "@tanstack/react-query"
import { BarChart3, Bot, Box, Check, FileText, Headphones, Home, Image as ImageIcon, MessageCircle, Package, RefreshCw, Send, Settings, ShoppingBag, Sparkles, UserRound, Users, WandSparkles } from "lucide-react"
import { conversationsApi, testAiApi, TestAiMessage, TestAiState } from "@/lib/api"
import { customerFacingText } from "@/lib/assistant-response"
import { SafeProductImage } from "@/components/ui/safe-product-image"
import { ImageUpload } from "@/components/ui/image-upload"
import "./testing.css"

const EMPTY:TestAiState={conversation:null,messages:[],usage:{aiReplies:0,llmCalls:0,nonGenerationAiCalls:0,zeroLlmResponses:0,llmAssistedResponses:0,providers:[],inputTokens:0,outputTokens:0,cachedTokens:0,totalTokens:0,averageTokensPerReply:0,estimatedCost:null}}
const prompts=["Black hoodie ta ache?","Delivery charge koto?","COD available?","Return policy ki?"]
const rail=[[Home,"/","Overview"],[MessageCircle,"/assistant","Assistant"],[Users,"/customers","Customers"],[Box,"/products","Products"],[ShoppingBag,"/orders","Orders"],[FileText,"/knowledge","Knowledge"],[BarChart3,"/admin/analytics","Analytics"]] as const

export function TestingWorkspace({onOpenLive}:{onOpenLive:(conversationId?:string)=>void}){
 const [state,setState]=useState<TestAiState>(EMPTY);const [input,setInput]=useState("");const [images,setImages]=useState<string[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const scroll=useRef<HTMLDivElement>(null);const initialized=useRef(false)
 const liveQuery=useQuery({queryKey:["assistant-activity"],queryFn:()=>conversationsApi.getAll({limit:40,sortBy:"updatedAt",order:"desc"}),refetchInterval:20000});const live=useMemo(()=>(liveQuery.data?.data||[]).filter(item=>item.platform!=="manual"&&!item.conversationId.startsWith("test_")),[liveQuery.data?.data])
 useEffect(()=>{if(initialized.current)return;initialized.current=true;testAiApi.newConversation().then(setState).catch(cause=>setError(cause instanceof Error?cause.message:"Unable to start Test AI")).finally(()=>setLoading(false))},[])
 useEffect(()=>{if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight},[state.messages,loading])
 const latestAssistant=[...state.messages].reverse().find(message=>message.role==="assistant");const products=latestAssistant?.products||[];const intent=latestAssistant?.intent||inferIntent(state.messages);const signals=deriveSignals(state.messages);const score=Math.min(96,(state.context?.intentScore||0)+signals.length*12)
 const channels=useMemo(()=>["web-widget","facebook","whatsapp"].map(platform=>({platform,count:live.filter(item=>item.platform===platform&&item.status==="active").length})),[live])
 async function send(event?:FormEvent,prompt?:string){event?.preventDefault();const message=(prompt??input).trim();const imageUrl=images[0];if((!message&&!imageUrl)||loading)return;setInput("");setImages([]);setLoading(true);setError("");setState(current=>({...current,messages:[...current.messages,{id:`pending-${Date.now()}`,role:"user",content:message,imageUrl,createdAt:new Date().toISOString()}]}));try{setState(await testAiApi.send(message,imageUrl))}catch(cause){setError(cause instanceof Error?cause.message:"AI request failed");await testAiApi.history().then(setState).catch(()=>undefined)}finally{setLoading(false)}}
 async function reset(){setState(EMPTY);setInput("");setImages([]);setLoading(true);setError("");try{setState(await testAiApi.newConversation())}catch(cause){setError(cause instanceof Error?cause.message:"Could not start a new chat")}finally{setLoading(false)}}
 return <div className="jolly-shell test-mode"><header className="jolly-header"><Link className="jolly-logo-cell" href="/"><Brand/></Link><div className="jolly-head-main"><div className="assistant-mode-switch"><button className="is-active">Test AI</button><button onClick={()=>onOpenLive()}>Live supervision <span>{live.filter(item=>item.controlMode==="AI_ACTIVE").length}</span></button></div><div className="jolly-head-actions"><button className="jolly-secondary-button" onClick={reset} disabled={loading}><RefreshCw size={17}/>New chat</button><Link className="jolly-primary-button" href="/training"><Sparkles size={17}/>Train AI</Link></div></div></header>
 <aside className="jolly-rail"><div className="jolly-account"><span>SP</span></div><nav>{rail.map(([Icon,href,label])=><Link key={href} href={href} className={href==="/assistant"?"is-active":""} title={label}><Icon size={20}/></Link>)}</nav><div className="jolly-rail-bottom"><Link href="/settings/business"><Settings size={20}/></Link><Link href="/settings/integrations"><Headphones size={20}/></Link></div></aside>
 <main className="jolly-main test-main"><button className="jolly-banner" onClick={()=>onOpenLive()}><b>AI ACTIVE</b><span>Test responses use your live catalog, inventory, policies, and knowledge</span><em>Monitor customers →</em></button><section className="jolly-greeting test-greeting"><h1>Test your sales AI</h1><p>See how <Brand small/><strong>SellPilot</strong> handles a customer.</p></section>
 <section className="jolly-conversation-card testing-chat"><header><div className="jolly-customer-avatar">T<i/></div><div><h2>Customer simulation</h2><p>Private testing environment · Merchant data connected</p></div><span className="jolly-state ai">Sandbox</span></header><div className="jolly-chat" ref={scroll}>{!loading&&!state.messages.length&&<div className="test-empty"><Brand/><h2>Ask a real customer question</h2><p>SellPilot will search your products and knowledge, then respond exactly as your AI sales employee would.</p><div>{prompts.map(prompt=><button key={prompt} onClick={()=>void send(undefined,prompt)}>{prompt}</button>)}</div></div>}{state.messages.map(message=><TestMessage key={message.id} message={message}/>)}{loading&&state.messages.length>0&&<article className="jolly-message assistant"><div className="jolly-message-meta"><span><Brand small/>SellPilot AI</span></div><div className="jolly-message-bubble test-typing"><i/><i/><i/></div></article>}{error&&<p className="test-error">{error}</p>}</div><footer className="test-composer">{images.length>0&&<ImageUpload value={images} onChange={setImages} disabled={loading} folder="test-ai" maxFiles={1}/>}<form onSubmit={send}><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}} placeholder="Ask as a customer…"/><div><ImageUpload value={images} onChange={setImages} disabled={loading} folder="test-ai" maxFiles={1}/><span><ImageIcon size={13}/>Products and knowledge are live</span><button disabled={loading||(!input.trim()&&!images.length)}><Send size={17}/></button></div></form></footer></section></main>
 <aside className="jolly-context activity-panel"><header><div><span>AI ACTIVITY</span><h2>Sales operation</h2></div><button className="jolly-secondary-button" onClick={()=>onOpenLive()}><MessageCircle size={16}/>Open live</button></header><section className="activity-channels"><h3>Active channels</h3>{channels.map(channel=><button key={channel.platform} onClick={()=>onOpenLive()}><i className={channel.count?"online":""}/><span><strong>{channelLabel(channel.platform)}</strong><small>{channel.count} active conversation{channel.count===1?"":"s"}</small></span><b>{channel.count}</b></button>)}</section><section className="test-analysis"><header><WandSparkles size={18}/><div><small>AI UNDERSTANDING</small><strong>{intent.replaceAll("_"," ")}</strong></div><b>{score}%</b></header><div className="analysis-grid"><Metric label="Response quality" value={state.usage.aiReplies?"Grounded":"Waiting"}/><Metric label="Purchase intent" value={score>69?"High":score>35?"Medium":"Low"}/><Metric label="Knowledge used" value={state.context?.knowledgeUsed?"Yes":"Not yet"}/><Metric label="Order stage" value={state.context?.salesStage||"Discovery"}/></div></section><section className="activity-block"><h3>Signals detected</h3>{signals.length?<ul>{signals.map(signal=><li key={signal}><Check size={14}/>{signal}</li>)}</ul>:<p>Ask about price, stock, delivery, payment, or ordering to inspect AI intent signals.</p>}</section><section className="activity-block"><h3>Matched products</h3>{products.length?<div>{products.slice(0,3).map((product,index)=><Product key={product.id||index} product={product}/>)}</div>:<p>Catalog matches will appear with live price and inventory.</p>}</section><section className="activity-usage"><span>Test session</span><strong>{state.usage.aiReplies} replies · {state.usage.totalTokens.toLocaleString()} tokens</strong></section></aside></div>
}

function Brand({small=false}:{small?:boolean}){return <span className={`jolly-brand-mark ${small?"small":""}`}><Bot size={small?18:22}/></span>}
function TestMessage({message}:{message:TestAiMessage}){const customer=message.role==="user";return <article className={`jolly-message ${customer?"customer":"assistant"}`}><div className="jolly-message-meta"><span>{customer?<UserRound size={14}/>:<Brand small/>}{customer?"Test customer":"SellPilot AI"}</span><time>{new Intl.DateTimeFormat("en",{hour:"2-digit",minute:"2-digit"}).format(new Date(message.createdAt))}</time></div><div className="jolly-message-bubble">{message.imageUrl&&<div className="jolly-message-image"><SafeProductImage src={message.imageUrl} alt="Test attachment"/></div>}<p>{customer?message.content:customerFacingText(message.content)}</p>{message.products?.length?<div className="test-product-grid">{message.products.slice(0,2).map((product,index)=><Product key={product.id||index} product={product}/>)}</div>:null}</div></article>}
function Product({product}:{product:NonNullable<TestAiMessage["products"]>[number]}){return <div className="test-product"><span>{product.image?<SafeProductImage src={product.image} alt={product.name}/>:<Package size={17}/>}</span><div><strong>{product.name}</strong><small>{product.price!=null?`৳${Number(product.price).toLocaleString()}`:"Price unavailable"} · {product.stock!=null?`${product.stock} in stock`:"Inventory connected"}</small></div></div>}
function Metric({label,value}:{label:string;value:string}){return <div><small>{label}</small><strong>{value}</strong></div>}
function channelLabel(value:string){return value==="web-widget"?"Website Chat":value==="facebook"?"Messenger":"WhatsApp"}
function inferIntent(messages:TestAiMessage[]){const text=[...messages].reverse().find(message=>message.role==="user")?.content.toLowerCase()||"";if(/order|korte chai|buy/.test(text))return"order_request";if(/cod|cash on delivery|bkash|nagad|payment/.test(text))return"payment_question";if(/delivery|charge/.test(text))return"delivery_question";if(/price|koto/.test(text))return"price_inquiry";if(/return|warranty/.test(text))return"support_request";if(/stock|available|ache|ase/.test(text))return"product_inquiry";return"general_inquiry"}
function deriveSignals(messages:TestAiMessage[]){const text=messages.filter(message=>message.role==="user").map(message=>message.content.toLowerCase()).join(" ");return [[/price|koto/,"Asked product price"],[/available|ache|ase|stock/,"Checked availability"],[/delivery|charge/,"Asked about delivery"],[/cod|cash on delivery|bkash|nagad|payment/,"Checked payment options"],[/order|korte chai|buy/,"Requested an order"]].filter(([pattern])=>(pattern as RegExp).test(text)).map(([,label])=>label as string)}
