'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'; import { ShieldCheck } from 'lucide-react';
export default function PlatformAdminLoginPage() {
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const router=useRouter();
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const response=await fetch('/api/platform-auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});const body=await response.json();if(!response.ok){setError(body.error||'Sign in failed');setBusy(false);return;}router.push('/platform-admin');router.refresh();}
 return <main className="grid min-h-screen place-items-center bg-slate-950 p-4 text-white"><Card className="w-full max-w-md border-slate-800 bg-slate-900 text-white"><CardHeader><div className="mb-3 grid h-12 w-12 place-items-center rounded-xl bg-violet-600"><ShieldCheck/></div><CardTitle className="text-2xl">SellPilot Platform Admin</CardTitle><p className="text-sm text-slate-400">Internal operations access. Merchant accounts cannot sign in here.</p></CardHeader><CardContent><form onSubmit={submit} className="space-y-4">{error&&<p className="rounded bg-red-950 p-3 text-sm text-red-300">{error}</p>}<Input className="border-slate-700 bg-slate-950" type="email" placeholder="Platform admin email" value={email} onChange={e=>setEmail(e.target.value)} required/><Input className="border-slate-700 bg-slate-950" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><Button className="w-full" disabled={busy}>{busy?'Signing in…':'Sign in to platform'}</Button></form></CardContent></Card></main>;
}
