"use client";
import {useState} from "react";
import Link from "next/link";
import {useQuery} from "@tanstack/react-query";
import {conversationsApi} from "@/lib/api";
import {PageHeader} from "@/components/layout/page-header";
import {WorkspacePanel,WorkspaceSearch,WorkspacePagination,WorkspaceEmpty} from "@/components/layout/workspace-surface";
import {Button} from "@/components/ui/button";
import {ArrowDownAZ,ArrowUpAZ,ArrowUpRight} from "lucide-react";
import {format} from "date-fns";
export default function ConversationsPage(){
 const [page,setPage]=useState(1);const [searchQuery,setSearchQuery]=useState("");const [sortBy,setSortBy]=useState("updatedAt");const [order,setOrder]=useState<"asc"|"desc">("desc");
 const {data:response,isLoading,error,refetch}=useQuery({queryKey:["conversations",page,searchQuery,sortBy,order],queryFn:()=>conversationsApi.getAll({page,limit:10,search:searchQuery,sortBy,order})});
 const {data:conversations,pagination}=response||{};
 function sort(key:string){setSortBy(key);setOrder(sortBy===key?(order==="asc"?"desc":"asc"):"desc");setPage(1);}
 return <div><PageHeader title="Conversations" description="One place for every customer thread. Review the context, then decide who takes the next step."/><WorkspacePanel title="Your inbox" description={`${pagination?.total||0} conversations across connected channels`} actions={<><div className="flex gap-2">{[["updatedAt","Recent"],["messageCount","Most messages"]].map(([key,label])=><Button key={key} size="sm" variant={sortBy===key?"secondary":"ghost"} onClick={()=>sort(key)}>{label}{sortBy===key&&(order==="desc"?<ArrowDownAZ size={13} className="ml-2"/>:<ArrowUpAZ size={13} className="ml-2"/>)}</Button>)}</div><WorkspaceSearch value={searchQuery} onChange={v=>{setSearchQuery(v);setPage(1);}} placeholder="Search customer or message"/></>}>{isLoading?<p role="status" className="p-12 text-center text-sm text-muted-foreground">Loading conversations…</p>:error?<WorkspaceEmpty title="We couldn’t load your inbox." copy="Check your connection and try again." action={<Button variant="outline" onClick={()=>refetch()}>Try again</Button>}/>:conversations?.length?<div className="work-table-scroll"><table className="work-table"><thead><tr><th>Customer</th><th>Latest message</th><th>Activity</th><th>Messages</th><th><span className="sr-only">Open conversation</span></th></tr></thead><tbody>{conversations.map(c=><tr key={c._id}><td><div className="flex items-center gap-3"><span className="grid w-9 h-9 place-items-center bg-primary/10 text-primary rounded-full text-xs shrink-0">{(c.customer?.name||"?").slice(0,2).toUpperCase()}</span><div><Link href={`/conversations/${c._id}`} className="font-semibold hover:text-primary">{c.customer?.name||"Unknown customer"}</Link><small>{c.customer?.phone||c.platform||"No phone"}</small></div></div></td><td><p className="work-message-preview">{c.lastMessage||"No messages yet"}</p></td><td className="whitespace-nowrap">{format(new Date(c.updatedAt),"MMM d, HH:mm")}</td><td><span className="work-status">{c.messageCount||0}</span></td><td><Link className="inline-flex p-2 rounded-lg hover:bg-primary/10 text-primary" href={`/conversations/${c._id}`} aria-label={`Open conversation with ${c.customer?.name||"customer"}`}><ArrowUpRight size={16}/></Link></td></tr>)}</tbody></table></div>:<WorkspaceEmpty title="Your next conversation starts here." copy="Customer messages from connected channels will appear in your inbox."/>}<WorkspacePagination page={page} totalPages={pagination?.totalPages||1} onChange={setPage}/><div className="px-6 pb-4 flex gap-4 text-[10px] text-muted-foreground"><button disabled={page===1} onClick={()=>setPage(1)}>First page</button><button disabled={page===(pagination?.totalPages||1)} onClick={()=>setPage(pagination?.totalPages||1)}>Last page</button></div></WorkspacePanel></div>;
}
