"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { ArrowLeft, ArrowRight, Facebook, LockKeyhole, Mail, ShieldCheck, Sparkles } from "lucide-react";
import { useLanguage } from "@/context/language-context";
import { PASSWORD_MIN_LENGTH } from "@edutechs/shared";

export function AuthExperience({ mode }: { mode: "signin" | "signup" }) {
  const { text } = useLanguage();
  const [notice, setNotice] = useState(false);
  const t = (en: string, bn: string) => text({ en, bn });
  const isSignup = mode === "signup";
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setNotice(true); }
  return <main className="auth-page"><div className="auth-atmosphere"><div className="aurora aurora-blue" /><div className="aurora aurora-violet" /></div><div className="site-container auth-layout">
    <section className="auth-story"><Link href="/" className="auth-back"><ArrowLeft />{t("Back to SellPilot", "SellPilot-এ ফিরুন")}</Link><div><p className="section-kicker"><Sparkles />{isSignup?t("Start your SellPilot journey", "SellPilot journey শুরু করুন"):t("Welcome back", "আবার স্বাগতম")}</p><h1>{isSignup?t("Turn the next conversation into an organized sales workflow.", "পরের কথোপকথনকে গোছানো sales workflow-তে বদলে দিন।"):t("Your commerce workspace is waiting.", "আপনার commerce workspace প্রস্তুত।")}</h1><p>{isSignup?t("Create the front door to your future workspace. Account provisioning and production authentication will be connected in the next backend milestone.", "আপনার ভবিষ্যৎ workspace-এর front door তৈরি করুন। Account provisioning ও production authentication পরের backend milestone-এ যুক্ত হবে।"):t("This secure access screen is ready for the production authentication milestone. It does not simulate a successful sign-in.", "এই secure access screen production authentication milestone-এর জন্য প্রস্তুত। এটি fake successful sign-in দেখায় না।")}</p><ul><li><ShieldCheck />{t("No fake OAuth success", "Fake OAuth success নেই")}</li><li><LockKeyhole />{t("Production auth remains a backend milestone", "Production auth আলাদা backend milestone")}</li></ul></div></section>
    <section className="auth-card"><div><span className="brand-mini">SP</span><p>{isSignup?t("Create account", "Account তৈরি করুন"):t("Sign in", "সাইন ইন")}</p><small>{isSignup?t("Early-access workspace request", "Early-access workspace request"):t("Provisioned teams only", "শুধু provisioned team")}</small></div><button type="button" className="oauth-button" disabled><span className="google-g">G</span>{t("Continue with Google", "Google দিয়ে চালিয়ে যান")}<small>{t("Not connected", "সংযুক্ত নয়")}</small></button><button type="button" className="oauth-button" disabled><Facebook />{t("Continue with Facebook", "Facebook দিয়ে চালিয়ে যান")}<small>{t("Not connected", "সংযুক্ত নয়")}</small></button><div className="auth-divider"><span>{t("or use email", "অথবা email ব্যবহার করুন")}</span></div><form onSubmit={submit}>{isSignup&&<label>{t("Your name", "আপনার নাম")}<input className="form-field" required name="name" autoComplete="name" placeholder={t("Full name", "পুরো নাম")} /></label>}<label>{t("Email", "Email")}<div className="field-with-icon"><Mail /><input className="form-field" type="email" required name="email" autoComplete="email" placeholder="you@business.com" /></div></label><label>{t("Password", "Password")}<div className="field-with-icon"><LockKeyhole /><input className="form-field" type="password" minLength={PASSWORD_MIN_LENGTH} required name="password" autoComplete={isSignup?"new-password":"current-password"} placeholder={t("At least 8 characters", "কমপক্ষে ৮ অক্ষর")} /></div></label><button className="button-primary" type="submit">{isSignup?t("Request early access", "Early access request করুন"):t("Continue", "চালিয়ে যান")}<ArrowRight /></button></form>{notice&&<div className="auth-notice" role="status"><ShieldCheck />{t("Production authentication is not connected yet. No account or session was created.", "Production authentication এখনও সংযুক্ত নয়। কোনো account বা session তৈরি হয়নি।")}</div>}<p className="auth-switch">{isSignup?t("Already have workspace access?", "Workspace access আছে?"):t("New to SellPilot?", "SellPilot-এ নতুন?")} <Link href={isSignup?"/signin":"/signup"}>{isSignup?t("Sign in", "সাইন ইন"):t("Create an account", "Account তৈরি করুন")}</Link></p></section>
  </div></main>;
}
