"use client";
import {useState,type FormEvent} from "react";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {ShieldCheck,ArrowRight} from "lucide-react";
import {Brand,Background,CommercePreview} from "./commerce-system";
const DASHBOARD_URL=process.env.NEXT_PUBLIC_DASHBOARD_URL||"http://localhost:3000";
export function AuthShell({initialMode="login"}:{initialMode?:"login"|"signup"}){
 const path=usePathname();const mode=path.includes("signup")?"signup":initialMode;
 const [email,setEmail]=useState("");const [name,setName]=useState("");const [busy,setBusy]=useState(false);
 function submit(e:FormEvent){e.preventDefault();setBusy(true);const params=new URLSearchParams({email});if(mode==="signup"){params.set("name",name);const trial=new URLSearchParams(location.search).get("trial");if(trial)params.set("trial",trial);}window.location.assign(`${DASHBOARD_URL}/${mode}?${params.toString()}`);}
 return <main className="reset-auth"><aside className="reset-auth-visual sp-dark"><Background/><div className="relative"><Brand/><p className="sp-eyebrow mt-16">Commerce, connected</p><h2 className="sp-heading mt-5">Your next chapter<br/>starts with a conversation.</h2><p className="sp-copy mt-5">Products, customers, and AI. Finally working together.</p></div><div className="relative mt-10"><CommercePreview/></div><p className="relative sp-note mt-8">Your team stays in control. Every step of the way.</p></aside><section className="reset-auth-form sp-light"><div className="reset-auth-mobile-brand"><Brand/></div><div className="w-full max-w-[400px] sp-reveal"><p className="sp-eyebrow">Your SellPilot workspace</p><h1 className="mt-5 text-4xl">{mode==="signup"?"Make room for growth.":"Welcome back."}</h1><p className="sp-copy mt-4 !text-sm">{mode==="signup"?"Start with your details. You’ll create your password securely in the merchant workspace.":"Continue to your secure merchant sign-in."}</p><form onSubmit={submit} className="mt-9 space-y-5">{mode==="signup"&&<label className="sp-label">Full name<input className="sp-field" autoComplete="name" value={name} onChange={e=>setName(e.target.value)} required/></label>}<label className="sp-label">Work email<input className="sp-field" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="you@company.com"/></label><button disabled={busy} className="sp-button sp-button-primary w-full" type="submit">{busy?"Opening secure workspace…":mode==="signup"?"Continue to create account":"Continue to sign in"}<ArrowRight size={16}/></button></form><p className="mt-5 flex gap-2 text-xs text-[#79798e]"><ShieldCheck size={16}/>Your password is entered only in the secure workspace.</p><div className="mt-8 pt-6 border-t border-[#e3e1ed] text-sm text-[#686c83]">{mode==="signup"?"Already have an account?":"New to SellPilot?"} <Link href={mode==="signup"?"/signin":"/signup"} className="text-[#7546d6] font-semibold">{mode==="signup"?"Sign in":"Get started"}</Link></div><Link href="/" className="inline-block text-xs text-[#84849b] mt-8">← Back to SellPilot</Link></div></section></main>;
}
