"use client";

import Link from "next/link";
import { ArrowRight, ArrowUpRight, Bot, Check, MessageCircle, Package, ShieldCheck, ShoppingBag, Sparkles } from "lucide-react";
import { useLanguage } from "@/context/language-context";
import { PRICING_PLANS } from "@/lib/marketing-config";
import type { ReactNode } from "react";

export function Brand() { return <Link href="/" className="reset-brand" aria-label="SellPilot home"><span><Bot size={19}/></span>SellPilot<span className="reset-brand-dot">®</span></Link>; }
export function Background() { return <div className="sp-atmos" aria-hidden="true"><span className="sp-orbit"/><span className="sp-star" style={{left:"12%",top:"24%"}}>✦</span><span className="sp-star" style={{right:"8%",top:"65%",animationDelay:"-3s"}}>✦</span></div>; }
export function Action({href,children,secondary=false}:{href:string;children:ReactNode;secondary?:boolean}) { return <Link href={href} className={`sp-button sp-button-${secondary?"secondary":"primary"}`}>{children}<ArrowRight size={16}/></Link>; }

/** Illustrative conversation: never presented as live merchant data. */
export function CommercePreview({store=false}:{store?:boolean}) {
 return <div className="commerce-preview sp-float"><div className="preview-toolbar"><span className="preview-dots"><i/><i/><i/></span><span>{store?"Your connected storefront":"SellPilot / Conversations"}</span><span className="sp-tag">Preview</span></div><div className="preview-body"><aside className="preview-rail"><Bot/><MessageCircle/><ShoppingBag/><Package/></aside><div className="preview-conversation"><div className="preview-heading"><span className="preview-avatar">N</span><div><strong>{store?"North Studio":"Nadia Rahman"}</strong><small>{store?"Thoughtful essentials, every day":"Website conversation · Example"}</small></div><span className="preview-online"/></div>{store?<><div className="preview-store-hero"><span>THE EVERYDAY COLLECTION</span><h3>Made for your<br/>every day.</h3><p>A simpler way to discover something good.</p></div><div className="preview-catalog">{["Everyday Tote","Studio Bottle","Classic Notebook"].map((name,i)=><div key={name}><span className={`preview-object object-${i}`}><ShoppingBag size={32}/></span><strong>{name}</strong><small>Example product</small></div>)}</div></>:<><div className="preview-bubble customer">I’m looking for an everyday bag. Something lightweight?</div><div className="preview-bubble agent"><span className="preview-agent-label"><Sparkles size={12}/> SELLPILOT AI</span>The Everyday Tote is a good match. It’s lightweight, with room for your daily essentials.</div><div className="preview-product"><span className="preview-object"><ShoppingBag size={36}/></span><div><strong>Everyday Tote</strong><small>Natural · Cotton canvas</small><span>৳1,250</span></div><ArrowUpRight size={16}/></div><div className="preview-bubble customer">Perfect. Can you deliver to Dhaka?</div><div className="preview-bubble agent">Yes. Share your delivery address and I’ll help you with the next step.</div><div className="preview-composer">Reply to Nadia…<span><ArrowRight size={14}/></span></div></>}</div></div><div className="preview-context"><span><ShieldCheck size={14}/> Grounded in your business</span><span>Human control, always</span></div></div>;
}

export function PlanGrid() { return <div className="sp-grid-3">{PRICING_PLANS.map(plan=><article key={plan.name} className={`reset-plan sp-glass ${plan.featured?"featured":""}`}><div className="plan-label"><span className="sp-eyebrow">{plan.name}</span>{plan.featured&&<span className="sp-tag">For growing teams</span>}</div><h3>{plan.price}</h3><p className="sp-copy">{plan.description}</p><Action href="/demo" secondary={!plan.featured}>Discuss your rollout</Action><ul>{plan.features.map(feature=><li key={feature}><Check size={15}/>{feature}</li>)}</ul><p className="sp-note">Early access · Final pricing to be confirmed</p></article>)}</div>; }

export function ClosingSection(){ const {text}=useLanguage();return <section className="sp-dark reset-closing"><Background/><div className="sp-wrap relative"><div><p className="sp-eyebrow">Your next chapter</p><h2 className="sp-heading">{text({en:"Better conversations.\nA better way to sell.",bn:"আরও ভালো কথোপকথন। আরও সহজ বিক্রি।"})}</h2></div><div><p className="sp-copy">Bring your products, knowledge, and people together. Let AI handle the conversation while you stay in control.</p><div className="sp-actions"><Action href="/signup">Get started</Action><Action href="/test-ai" secondary>Experience the AI</Action></div></div></div></section>;}

export function ProductExperience({kind}:{kind:"chat"|"store"}){const store=kind==="store";return <main className="reset-public"><section className="sp-dark reset-home-hero"><Background/><div className="sp-wrap reset-hero-grid"><div><p className="sp-eyebrow">{store?"SellPilot Store Builder":"SellPilot AI Chatbot"}</p><h1>{store?"Your products.\nTheir next discovery.":"An AI that knows\nyour business."}</h1><p className="sp-copy">{store?"Turn your catalog into a connected shopping experience. Manage products, storefront settings, and orders from the same workspace.":"Turn product questions into helpful conversations. Give your AI the knowledge it needs, with your team always in control."}</p><div className="sp-actions"><Action href="/signup">{store?"Create your store":"Set up your AI"}</Action><Action href={store?"/shop":"/test-ai"} secondary>{store?"Explore the shop":"Try the AI"}</Action></div><p className="sp-note mt-6">{store?"Connected catalog · Cart · Checkout":"Messenger + website chat · WhatsApp coming soon"}</p></div><CommercePreview store={store}/></div></section><section className="sp-light sp-section"><div className="sp-wrap"><div className="sp-section-head"><div><p className="sp-eyebrow">Built around your workflow</p><h2 className="sp-heading">{store?"From catalog to checkout.":"Context in. Confidence out."}</h2></div><p className="sp-copy">One source of business context. Less manual work between the steps.</p></div><div className="sp-grid-3">{(store?[["Curate your catalog","Manage product details, images, pricing, and availability in your workspace."],["Make it yours","Set your brand colors, storefront message, and catalog layout."],["Stay connected","Receive orders through the existing checkout and order workflow."]]:[["Train with your knowledge","Add business details, product information, and policies to guide the AI."],["Have useful conversations","Help customers find products and understand the next step."],["Review and improve","See conversations, unanswered questions, and usage. Take over when needed."]]).map(([title,copy],i)=><article className="reset-step sp-surface" key={title}><span className="sp-tag">0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section><section id="pricing" className="sp-dark sp-section"><div className="sp-wrap"><div className="sp-section-head"><div><p className="sp-eyebrow">Early access</p><h2 className="sp-heading">Start with the right scope.</h2></div><p className="sp-copy">Choose a rollout that matches your operations. Final commercial pricing is confirmed separately.</p></div><PlanGrid/></div></section><ClosingSection/></main>;}
