"use client";
import Link from "next/link";
import type { ReactNode } from "react";
import { Background, Brand, Action } from "./commerce-system";
export function SectionHeading({eyebrow,title,copy,center=false}:{eyebrow:string;title:string;copy?:string;center?:boolean}){return <div className={center?"mx-auto max-w-3xl text-center":"max-w-3xl"}><p className="sp-eyebrow">{eyebrow}</p><h2 className="sp-heading mt-4">{title}</h2>{copy&&<p className="sp-copy mt-5">{copy}</p>}</div>;}
export function Atmosphere({className="",children}:{className?:string;children?:ReactNode}){return <div className={`relative ${className}`}><Background/>{children}</div>;}
export function PricingCard({featured=false,className="",children}:{featured?:boolean;className?:string;children:ReactNode}){return <article className={`sp-pricing-card ${featured?"is-featured":""} ${className}`}>{children}</article>;}
export function PageHero({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <section className="sp-dark relative overflow-hidden py-16 sm:py-20"><Background/><div className="sp-wrap relative grid gap-8 lg:grid-cols-[1.2fr_1fr] lg:items-end"><div><p className="sp-eyebrow">{eyebrow}</p><h1 className="page-title mt-5">{title}</h1></div><p className="sp-copy lg:pl-10">{copy}</p></div></section>;}
export function FinalCTA({title="Build a better way to sell.",copy="Bring your products, knowledge, and people into one connected commerce workspace."}:{title?:string;copy?:string}){return <section className="reset-closing sp-dark"><Background/><div className="sp-wrap relative"><div><p className="sp-eyebrow">Built for what comes next</p><h2 className="sp-heading">{title}</h2></div><div><p className="sp-copy">{copy}</p><div className="sp-actions"><Action href="/signup">Get started</Action><Action href="/demo" secondary>Plan your rollout</Action></div></div></div></section>;}
export function MarketingFooter(){return <footer className="reset-footer"><div className="sp-wrap"><div><Brand/><p>Commerce, connected.<br/>An AI workspace for the businesses behind every conversation.</p></div>{[{title:"Platform",links:[["AI Chatbot","/products/ai-chatbot"],["Store Builder","/products/store-builder"],["Features","/features"],["Pricing","/pricing"]]},{title:"Explore",links:[["Test AI","/test-ai"],["Solutions","/solutions"],["Shop","/shop"],["How it works","/#workflow"]]},{title:"Company",links:[["About","/about"],["Demo / Contact","/demo"],["Sign in","/signin"],["Get started","/signup"]]}].map(group=><div key={group.title}><h3>{group.title}</h3>{group.links.map(([label,href])=><Link href={href} key={label}>{label}</Link>)}</div>)}</div></footer>;}
