'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, BookOpen, Check, ChevronRight, FileUp, Globe2, Loader2, Package, RefreshCw, Sparkles, TestTube2 } from 'lucide-react';
import { trainingApi } from '@/lib/api';
import { TrainingCandidate } from '@/types';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { SafeProductImage } from '@/components/ui/safe-product-image';
import { ImageUpload } from '@/components/ui/image-upload';

const labels: Record<string, string> = {
    not_started: 'Not started', learning: 'Learning', needs_review: 'Needs review', ready: 'Ready', syncing: 'Syncing', error: 'Failed',
    ready_item: 'Ready', possible_duplicate: 'Possible duplicate', conflict: 'Conflict', needs_attention: 'Needs attention', imported: 'Imported', rejected: 'Rejected', partial: 'Needs attention',
};

function CandidateCard({ candidate, refresh }: { candidate: TrainingCandidate; refresh: () => void }) {
    const [editing, setEditing] = useState(false);
    const [name, setName] = useState(String(candidate.payload.name || candidate.payload.title || candidate.title));
    const [price, setPrice] = useState(String(candidate.payload.basePrice ?? ''));
    const [content, setContent] = useState(String(candidate.payload.content || candidate.payload.description || ''));
    const [images, setImages] = useState<string[]>(Array.isArray(candidate.payload.images) ? candidate.payload.images : []);
    const action = useMutation({ mutationFn: async (kind: string) => {
        if (kind === 'approve') return trainingApi.approve(candidate._id);
        if (kind === 'reject') return trainingApi.reject(candidate._id);
        if (kind === 'merge') return trainingApi.merge(candidate._id);
        if (kind === 'separate') return trainingApi.keepSeparate(candidate._id);
        if (kind === 'current' || kind === 'imported') return trainingApi.resolve(candidate._id, Object.fromEntries(candidate.conflictFields.map((field) => [field.field, { choice: kind }])));
        const payload: Record<string, unknown> = candidate.kind === 'product'
            ? { name, description: content, images, ...(price ? { basePrice: Number(price) } : {}) }
            : { title: name, content };
        return trainingApi.edit(candidate._id, payload, name);
    }, onSuccess: () => { setEditing(false); refresh(); } });
    const tone = candidate.status === 'conflict' ? 'border-rose-500/30 bg-rose-500/5' : candidate.status === 'possible_duplicate' || candidate.status === 'needs_attention' ? 'border-amber-500/30 bg-amber-500/5' : 'border-border bg-card';
    return <div className={`rounded-2xl border p-4 ${tone}`}>
        <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
            <div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><b className="truncate">{candidate.title}</b><Badge variant="outline">{labels[candidate.status === 'ready' ? 'ready_item' : candidate.status] || candidate.status}</Badge><Badge variant="secondary">{candidate.kind}</Badge></div>
                <p className="mt-1 text-xs text-muted-foreground">From {candidate.source.type}{candidate.source.url ? ` · ${candidate.source.url}` : ''}</p>
                {candidate.kind === 'product' && <p className="mt-2 text-sm">{candidate.payload.basePrice !== undefined ? `৳${candidate.payload.basePrice}` : 'Price missing'} · Stock {candidate.payload.stock ?? 0}</p>}
                {candidate.kind === 'product' && images.length > 0 && <div className="mt-3 flex gap-2 overflow-x-auto">{images.slice(0, 5).map((url, index) => <div key={`${url}-${index}`} className="relative h-20 w-20 shrink-0 overflow-hidden rounded-xl border bg-muted"><SafeProductImage src={url} alt={`${candidate.title} image ${index + 1}`}/>{index === 0 && <span className="absolute bottom-1 left-1 rounded bg-background/90 px-1.5 py-0.5 text-[10px]">Primary</span>}</div>)}{images.length > 5 && <div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-xl border bg-muted text-xs">+{images.length - 5} more</div>}</div>}
                {candidate.kind === 'knowledge' && <p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{candidate.payload.content}</p>}
                {candidate.conflictFields.map((field) => <div key={field.field} className="mt-3 rounded-xl border bg-background/70 p-3 text-sm"><b>{field.field.replace(/([A-Z])/g, ' $1')} conflict</b><div className="mt-1 grid gap-1 sm:grid-cols-2"><span>Current: {String(field.currentValue)}</span><span>Imported: {String(field.importedValue)}</span></div></div>)}
            </div>
            <div className="flex shrink-0 flex-wrap gap-2">
                {candidate.status === 'ready' && <Button size="sm" disabled={action.isPending} onClick={() => action.mutate('approve')}><Check className="mr-1 h-4 w-4"/>Approve</Button>}
                {candidate.status === 'possible_duplicate' && <><Button size="sm" disabled={action.isPending} onClick={() => action.mutate('merge')}>Merge</Button><Button size="sm" variant="outline" onClick={() => action.mutate('separate')}>Keep separate</Button></>}
                {candidate.status === 'conflict' && <><Button size="sm" onClick={() => action.mutate('imported')}>Use imported</Button><Button size="sm" variant="outline" onClick={() => action.mutate('current')}>Keep current</Button></>}
                {['ready','needs_attention','possible_duplicate','conflict'].includes(candidate.status) && <><Button size="sm" variant="ghost" onClick={() => setEditing((value) => !value)}>Edit</Button><Button size="sm" variant="ghost" onClick={() => action.mutate('reject')}>Reject</Button></>}
            </div>
        </div>
        {editing && <div className="mt-4 grid gap-3 rounded-xl border bg-background p-3"><Input value={name} onChange={(event) => setName(event.target.value)} placeholder="Name or title"/>{candidate.kind === 'product' && <><Input type="number" value={price} onChange={(event) => setPrice(event.target.value)} placeholder="Price"/><ImageUpload value={images} onChange={setImages} disabled={action.isPending} folder="training-review" maxFiles={12}/></>}<textarea className="min-h-24 rounded-md border bg-background p-3 text-sm" value={content} onChange={(event) => setContent(event.target.value)} placeholder="Description or content"/><Button className="w-fit" size="sm" disabled={action.isPending} onClick={() => action.mutate('edit')}>Save changes</Button></div>}
    </div>;
}

export function TrainingWorkspace({ onboarding = false, onFinish }: { onboarding?: boolean; onFinish?: () => Promise<void> }) {
    const client = useQueryClient(); const [website, setWebsite] = useState(''); const [pageId, setPageId] = useState(''); const [error, setError] = useState('');
    const [selectedFile, setSelectedFile] = useState<File | null>(null); const [uploadedSourceId, setUploadedSourceId] = useState('');
    const [uploadSummary, setUploadSummary] = useState<{ products: number; knowledge: number; warnings: string[] } | null>(null);
    const [manualKind, setManualKind] = useState<'faq'|'information'|null>(null); const [manualTitle, setManualTitle] = useState(''); const [manualContent, setManualContent] = useState('');
    const statusQuery = useQuery({ queryKey: ['training-status'], queryFn: trainingApi.status, refetchInterval: (query) => ['queued','learning'].includes(query.state.data?.latestRun?.status || '') ? 1200 : 5000 });
    const candidatesQuery = useQuery({ queryKey: ['training-candidates'], queryFn: () => trainingApi.candidates(), refetchInterval: ['queued','learning'].includes(statusQuery.data?.latestRun?.status || '') ? 1500 : false });
    const refresh = () => { client.invalidateQueries({ queryKey: ['training-status'] }); client.invalidateQueries({ queryKey: ['training-candidates'] }); };
    const sourceMutation = useMutation({ mutationFn: async (action: () => Promise<unknown>) => action(), onMutate: () => setError(''), onSuccess: refresh, onError: (reason) => setError(reason instanceof Error ? reason.message : 'Could not start learning') });
    const fileMutation = useMutation({
        mutationFn: (file: File) => trainingApi.uploadFile(file),
        onMutate: () => { setError(''); setUploadSummary(null); },
        onSuccess: (result) => { setUploadedSourceId(result.source._id); setUploadSummary(result.summary); refresh(); },
        onError: (reason) => setError(reason instanceof Error ? reason.message : 'Could not upload this file'),
    });
    const safeMutation = useMutation({ mutationFn: trainingApi.approveSafe, onSuccess: refresh });
    const manualMutation = useMutation({ mutationFn: () => trainingApi.addManual(manualKind || 'information', manualTitle, manualContent), onSuccess: () => { setManualTitle(''); setManualContent(''); setManualKind(null); refresh(); }, onError: (reason) => setError(reason instanceof Error ? reason.message : 'Could not add this information') });
    const candidates = useMemo(() => candidatesQuery.data || [], [candidatesQuery.data]);
    const review = useMemo(() => ({ ready: candidates.filter((item) => item.status === 'ready'), duplicates: candidates.filter((item) => item.status === 'possible_duplicate'), conflicts: candidates.filter((item) => item.status === 'conflict'), attention: candidates.filter((item) => item.status === 'needs_attention') }), [candidates]);
    const overview = statusQuery.data; const learning = ['queued','learning'].includes(overview?.latestRun?.status || '');
    const runFailed = overview?.latestRun?.status === 'error';
    const uploadedSource = overview?.sources?.find((source) => source._id === uploadedSourceId);
    return <div className="mx-auto max-w-6xl space-y-6">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-primary">CONNECT → LEARN → REVIEW → SELL</p><h1 className="mt-1 text-3xl font-bold">Teach SellPilot your business</h1><p className="mt-2 text-muted-foreground">Connect what you already have. SellPilot will organize it for your review.</p></div><Badge className="w-fit px-4 py-2" variant={overview?.training.status === 'ready' ? 'default' : 'secondary'}>{labels[overview?.training.status || 'not_started']}</Badge></div>
        {error && <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
        <Card><CardHeader><CardTitle>1. Connect your business</CardTitle></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2">
            <div className="rounded-2xl border p-5"><Globe2 className="h-6 w-6 text-primary"/><h3 className="mt-3 font-bold">Website</h3><p className="mb-4 text-sm text-muted-foreground">Products, FAQs, contact details and policies.</p><div className="flex gap-2"><Input value={website} onChange={(e) => setWebsite(e.target.value)} placeholder="https://yourbusiness.com"/><Button disabled={!website || sourceMutation.isPending} onClick={() => sourceMutation.mutate(() => trainingApi.connectWebsite(website))}>Learn</Button></div></div>
            <div className="rounded-2xl border p-5"><Sparkles className="h-6 w-6 text-primary"/><h3 className="mt-3 font-bold">Facebook Page</h3><p className="mb-4 text-sm text-muted-foreground">Uses your authorized SellPilot Page connection. Permission issues won&apos;t block other sources.</p><div className="flex gap-2"><Input value={pageId} onChange={(e) => setPageId(e.target.value)} placeholder="Connected Page ID"/><Button disabled={!pageId || sourceMutation.isPending} onClick={() => sourceMutation.mutate(() => trainingApi.connectFacebook(pageId))}>Connect</Button></div></div>
            <div className="rounded-2xl border border-dashed p-5"><label htmlFor="training-file" className="flex cursor-pointer items-center gap-3 hover:text-primary"><FileUp className="h-6 w-6 text-primary"/><span><b>Choose a file</b><span className="block text-sm text-muted-foreground">PDF, DOCX, TXT, CSV or XLSX · up to 10 MB</span></span></label><input id="training-file" className="sr-only" type="file" accept=".pdf,.docx,.txt,.csv,.xlsx" onChange={(event) => { setSelectedFile(event.target.files?.[0] || null); setUploadedSourceId(''); setUploadSummary(null); setError(''); }}/>{selectedFile && <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-muted/50 p-3"><div className="min-w-0"><b className="block truncate text-sm">{selectedFile.name}</b><span className="text-xs text-muted-foreground">{(selectedFile.size / 1_000_000).toFixed(2)} MB selected</span></div><Button size="sm" disabled={fileMutation.isPending} onClick={() => fileMutation.mutate(selectedFile)}>{fileMutation.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Uploading...</> : 'Upload and learn'}</Button></div>}{fileMutation.isPending && <p className="mt-3 text-sm text-muted-foreground">Securely reading and classifying your file...</p>}{uploadSummary && <div className={`mt-3 rounded-xl border p-3 text-sm ${uploadedSource?.status === 'error' ? 'border-rose-500/30 bg-rose-500/5 text-rose-700' : 'border-emerald-500/30 bg-emerald-500/5'}`}><b>{uploadedSource?.status === 'error' ? 'Learning failed' : uploadedSource && ['ready','needs_attention'].includes(uploadedSource.status) ? 'Ready for review' : 'Upload received. Learning...'}</b><p className="mt-1">{uploadedSource?.stats?.products ?? uploadSummary.products} products found · {uploadedSource?.stats?.knowledge ?? uploadSummary.knowledge} knowledge items found{uploadedSource?.stats ? ` · ${uploadedSource.stats.duplicates} possible duplicates · ${uploadedSource.stats.conflicts} conflicts · ${uploadedSource.stats.needsAttention} need attention` : ''}</p>{uploadSummary.warnings.map((warning) => <p key={warning} className="mt-1 text-amber-700">{warning}</p>)}{uploadedSource?.errorMessage && <p className="mt-1">{uploadedSource.errorMessage}</p>}{uploadedSource && ['ready','needs_attention'].includes(uploadedSource.status) && <Button asChild size="sm" className="mt-3"><a href="#training-review">Review</a></Button>}</div>}</div>
            <div className="grid grid-cols-2 gap-3"><Button asChild variant="outline" className="h-auto py-4"><Link href="/products"><Package className="mr-2 h-4 w-4"/>Add product</Link></Button><Button asChild variant="outline" className="h-auto py-4"><Link href="/knowledge"><BookOpen className="mr-2 h-4 w-4"/>Add knowledge</Link></Button></div>
        </CardContent></Card>
            {overview?.sources?.length ? <Card><CardHeader><CardTitle>Connected sources</CardTitle></CardHeader><CardContent className="space-y-3">{overview.sources.map((source) => <div key={source._id} className={`flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between ${source.status === 'error' ? 'border-rose-500/30 bg-rose-500/5' : ''}`}><div><b>{source.name}</b><p className="text-sm text-muted-foreground">{source.type} · {labels[source.status] || source.status.replace('_',' ')}{source.lastSyncedAt ? ` · ${new Date(source.lastSyncedAt).toLocaleString()}` : ''}</p>{source.errorMessage && <p className="mt-1 text-sm text-rose-700">{source.errorMessage}</p>}</div>{source.type === 'website' && <div className="flex gap-2">{source.stats?.failed > 0 && <Button variant="outline" size="sm" onClick={() => sourceMutation.mutate(() => trainingApi.retryFailed(source._id))}>Retry {source.stats.failed} failed</Button>}<Button variant="outline" size="sm" onClick={() => sourceMutation.mutate(() => trainingApi.rescan(source._id))}><RefreshCw className="mr-2 h-4 w-4"/>{source.status === 'error' ? 'Retry' : 'Rescan'}</Button></div>}</div>)}</CardContent></Card> : null}
        {overview?.latestRun && <Card className={runFailed ? 'border-rose-500/30' : ''}><CardHeader><CardTitle>2. SellPilot learns</CardTitle></CardHeader><CardContent><div className="flex items-center gap-3">{learning ? <Loader2 className="h-5 w-5 animate-spin text-primary"/> : runFailed || overview.latestRun.status === 'partial' ? <AlertTriangle className="h-5 w-5 text-amber-600"/> : <Check className="h-5 w-5 text-emerald-600"/>}<div><b>{overview.latestRun.stage}</b>{runFailed && overview.latestRun.errorMessage && <p className="mt-1 text-sm text-rose-700">{overview.latestRun.errorMessage}</p>}</div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full transition-all ${runFailed ? 'bg-rose-500' : 'bg-primary'}`} style={{width:`${runFailed ? 0 : overview.latestRun.progress}%`}}/></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-5">{(['discovered','pages','productUrls','products','remaining','failed'] as const).map((key) => <div key={key} className="rounded-xl bg-muted/50 p-3"><b className="block text-lg">{overview.latestRun?.stats?.[key] ?? 0}</b>{key === 'pages' ? 'processed' : key.replace(/([A-Z])/g,' $1')}</div>)}</div></CardContent></Card>}
        {candidates.length > 0 && <Card id="training-review"><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>3. Review what SellPilot learned</CardTitle><p className="mt-1 text-sm text-muted-foreground">Clean items can be approved together. Only duplicates and conflicts need your attention.</p></div><Button disabled={!review.ready.length || safeMutation.isPending} onClick={() => safeMutation.mutate()}>{safeMutation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <Check className="mr-2 h-4 w-4"/>}Approve all safe items ({review.ready.length})</Button></div></CardHeader><CardContent className="space-y-6">
            {([['Ready',review.ready],['Possible duplicates',review.duplicates],['Conflicts',review.conflicts],['Needs attention',review.attention]] as const).map(([title,items]) => items.length ? <section key={title}><h3 className="mb-3 flex items-center gap-2 font-bold">{title === 'Conflicts' && <AlertTriangle className="h-4 w-4 text-rose-500"/>}{title} <Badge variant="secondary">{items.length}</Badge></h3><div className="space-y-3">{items.map((candidate) => <CandidateCard key={candidate._id} candidate={candidate} refresh={refresh}/>)}</div></section> : null)}
        </CardContent></Card>}
        <Card><CardHeader><CardTitle>Fill only the gaps</CardTitle></CardHeader><CardContent className="space-y-4">{overview?.missing?.length ? <div className="grid gap-2 sm:grid-cols-2">{overview.missing.map((question) => <button key={question} type="button" onClick={() => { setManualKind('information'); setManualTitle(question); }} className="rounded-xl border p-3 text-left text-sm hover:bg-muted/40">{question}<ChevronRight className="ml-2 inline h-4 w-4"/></button>)}</div> : <p className="text-sm text-muted-foreground">No critical gaps detected.</p>}<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setManualKind('information')}>+ Add custom business information</Button><Button variant="outline" onClick={() => setManualKind('faq')}>+ Add custom question &amp; answer</Button></div>{manualKind && <div className="grid gap-3 rounded-xl border bg-muted/20 p-4"><Input value={manualTitle} onChange={(event) => setManualTitle(event.target.value)} placeholder={manualKind === 'faq' ? 'Customer question' : 'Information title'}/><textarea className="min-h-24 rounded-md border bg-background p-3 text-sm" value={manualContent} onChange={(event) => setManualContent(event.target.value)} placeholder={manualKind === 'faq' ? 'Approved answer' : 'Business information'}/><div className="flex gap-2"><Button disabled={manualMutation.isPending || manualTitle.trim().length < 3 || manualContent.trim().length < 3} onClick={() => manualMutation.mutate()}>{manualMutation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : null}Add for review</Button><Button variant="ghost" onClick={() => setManualKind(null)}>Cancel</Button></div></div>}</CardContent></Card>
        <Card><CardHeader><CardTitle>4. Test and sell</CardTitle></CardHeader><CardContent><p className="mb-4 text-muted-foreground">Approved products and business knowledge are immediately available to your tenant-scoped Test AI.</p>{overview?.suggestedQuestions?.length ? <div className="mb-4 flex flex-wrap gap-2">{overview.suggestedQuestions.map((question) => <Badge key={question} variant="outline" className="px-3 py-2">{question}</Badge>)}</div> : null}<div className="flex flex-wrap gap-3"><Button asChild><Link href="/test-ai"><TestTube2 className="mr-2 h-4 w-4"/>Test your AI</Link></Button>{onboarding && onFinish && <Button variant="outline" onClick={() => onFinish()}>Finish setup</Button>}</div></CardContent></Card>
    </div>;
}
