'use client';
import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {apiClient} from '@/lib/api-client';
import {PageHeader} from '@/components/layout/page-header';
import {Button} from '@/components/ui/button';
type Integration={provider:string;supported:boolean;fields:string[];configured:boolean;integrationId:string};
export default function IntelligenceSettings(){
 const query=useQuery({queryKey:['intelligence-integrations'],queryFn:()=>apiClient.get<{data:Integration[]}>('/api/intelligence/integrations')});
 return <div className="space-y-6"><PageHeader title="Intelligence integrations" description="Connect verified courier and payment evidence to your customer timeline."/>{query.isLoading?<p>Loading integrations…</p>:query.isError?<p role="alert">Integration settings require administrator access and an available backend.</p>:<div className="grid gap-4 lg:grid-cols-2">{query.data?.data.map(item=><IntegrationCard item={item} key={item.provider}/>)}</div>}<WhatsAppSettings/></div>;
}
function IntegrationCard({item}:{item:Integration}){
 const [values,setValues]=useState<Record<string,string>>({environment:'sandbox'});const client=useQueryClient();
 const mutation=useMutation({mutationFn:()=>apiClient.put(`/api/intelligence/integrations/${item.provider}`,values),onSuccess:()=>{setValues({environment:'sandbox'});void client.invalidateQueries({queryKey:['intelligence-integrations']});}});
 return <section className="rounded-2xl border border-border bg-card p-6"><div className="flex justify-between gap-3"><h2 className="text-lg font-semibold capitalize">{item.provider}</h2><span className="text-xs text-muted-foreground">{item.configured?'Credentials saved':item.supported?'Not configured':'Contract verification pending'}</span></div>{!item.supported?<p className="mt-4 text-sm text-muted-foreground">This provider is unavailable until its merchant API contract and credentials have been validated.</p>:<form className="mt-5 space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate();}}>{item.fields.map(field=><label key={field} className="block text-xs text-muted-foreground">{field}<input type="password" autoComplete="new-password" required value={values[field]||''} onChange={e=>setValues({...values,[field]:e.target.value})} className="mt-1 block w-full rounded-lg border border-border bg-background p-2 text-foreground"/></label>)}{item.provider!=='pathao'&&<label className="block text-xs">Environment<select className="ml-3 rounded border bg-background p-2" value={values.environment} onChange={e=>setValues({...values,environment:e.target.value})}><option value="sandbox">Sandbox</option><option value="live">Live</option></select></label>}<Button disabled={mutation.isPending}>{mutation.isPending?'Saving…':'Save credentials'}</Button>{mutation.isError&&<p role="alert" className="text-sm text-destructive">Could not save credentials. Check the fields and server encryption configuration.</p>}{mutation.isSuccess&&<p className="text-sm text-emerald-600">Credentials saved. A verified provider event is needed to populate customer history.</p>}{item.integrationId&&['pathao','sslcommerz'].includes(item.provider)&&<p className="break-all text-xs text-muted-foreground">Callback path: {item.provider==='pathao'?'/courier-events/pathao/':'/payment-events/sslcommerz/'}{item.integrationId}</p>}</form>}</section>;
}
function WhatsAppSettings(){const [phoneNumberId,setPhone]=useState('');const [accessToken,setToken]=useState('');const mutation=useMutation({mutationFn:()=>apiClient.post('/api/integrations/whatsapp',{phoneNumberId,accessToken}),onSuccess:()=>setToken('')});return <section className="rounded-2xl border border-border bg-card p-6"><h2 className="text-lg font-semibold">WhatsApp Business</h2><p className="mt-2 text-sm text-muted-foreground">Connect a registered Meta phone number. The server verifies ownership before enabling it.</p><form className="mt-4 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();mutation.mutate();}}><input aria-label="Phone number ID" placeholder="Phone number ID" required value={phoneNumberId} onChange={e=>setPhone(e.target.value)} className="rounded-lg border bg-background p-2"/><input aria-label="WhatsApp access token" placeholder="System user access token" type="password" autoComplete="new-password" required value={accessToken} onChange={e=>setToken(e.target.value)} className="rounded-lg border bg-background p-2"/><Button disabled={mutation.isPending}>Verify and connect</Button></form>{mutation.isError&&<p role="alert" className="mt-3 text-sm text-destructive">Connection verification failed. Check credentials and server Meta settings.</p>}{mutation.isSuccess&&<p className="mt-3 text-sm text-emerald-600">WhatsApp connected. Configure Meta’s webhook to /whatsapp.</p>}</section>;}
