import type { Metadata } from "next";
import { Bot, Boxes, BrainCircuit, ChartNoAxesCombined, CircleDollarSign, Globe2, Headphones, ImageIcon, LockKeyhole, MessageSquareText, PackageCheck, SearchCheck, ShieldCheck, ShoppingBag, Users, UsersRound } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { FinalCTA, PageHero } from "@/components/marketing";

export const metadata: Metadata = { title: "Features", description: "Explore Digitross AI conversation, commerce, team, and platform capabilities." };
const groups: Array<{ label: string; copy: string; items: Array<[LucideIcon, string, string]> }> = [
  { label: "AI conversation", copy: "Helpful conversations grounded in the business behind them.", items: [[Bot, "AI sales conversations", "Support discovery, questions, and buying decisions with concise responses."], [BrainCircuit, "Knowledge-grounded answers", "Retrieve relevant business policies and knowledge instead of guessing."], [SearchCheck, "Product recommendations", "Search a small, relevant candidate set for each customer request."], [ImageIcon, "Image product matching", "Use customer images to find visually relevant catalog candidates."]] },
  { label: "Commerce", copy: "Connect the conversation to real operational data.", items: [[Boxes, "Product catalog", "Manage product information, availability, variants, and supporting details."], [Users, "Customer records", "Collect and reuse customer context inside the right business workspace."], [PackageCheck, "Confirmed order actions", "Create orders through backend-confirmed workflows without fabricated success."], [ShoppingBag, "Exact commerce answers", "Answer high-confidence price, stock, and order-status questions deterministically."]] },
  { label: "Team", copy: "AI and people working with one clear controller.", items: [[Headphones, "Human takeover", "Stop AI immediately while keeping incoming messages available for the team."], [MessageSquareText, "Conversation history", "Continue with recent context and compact summaries across longer threads."], [UsersRound, "Owner, Admin, Staff", "Role-aware workspace access for the people operating the business."], [ShieldCheck, "Return to AI", "Resume future conversations cleanly without replaying historical actions."]] },
  { label: "Platform", copy: "A safer foundation for operating more than one business.", items: [[LockKeyhole, "Tenant isolation", "Business-scoped data boundaries across conversations and commerce operations."], [Globe2, "Messenger + web", "Facebook Messenger and website chat channels are available now."], [CircleDollarSign, "AI cost controls", "Bound context, retrieval, candidate sets, and model output length."], [ChartNoAxesCombined, "Usage tracking", "Track provider token usage and configurable estimated cost by business."]] },
];
export default function FeaturesPage() { return <main><PageHero eyebrow="Product capabilities" title="Everything needed to operate AI-assisted commerce conversations." copy="Digitross connects conversation intelligence, commerce operations, and human control without hiding what is live and what comes next." /><section className="site-container space-y-20 py-20 sm:py-28">{groups.map(group => <div key={group.label} className="grid gap-8 lg:grid-cols-[.38fr_.62fr]"><div><p className="section-kicker">{group.label}</p><h2 className="mt-3 text-2xl font-semibold tracking-tight text-slate-950">{group.copy}</h2></div><div className="grid gap-4 sm:grid-cols-2">{group.items.map(([Icon, title, copy]) => <article key={String(title)} className="surface-card p-6"><div className="icon-tile"><Icon className="h-5 w-5" /></div><h3 className="mt-5 font-semibold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p><span className="mt-5 inline-flex rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-wider text-emerald-700">Available now</span></article>)}</div></div>)}</section><section className="bg-slate-50 py-20"><div className="site-container"><p className="section-kicker">Coming soon</p><div className="mt-6 grid gap-4 md:grid-cols-3">{[["WhatsApp", "A future customer conversation channel."], ["Courier automation", "Delivery workflows, including planned Steadfast integration."], ["Broader channel coverage", "Additional social commerce channels after validation."]].map(([title, copy]) => <div key={title} className="rounded-2xl border border-dashed border-slate-300 bg-white p-6"><h3 className="font-semibold text-slate-800">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{copy}</p></div>)}</div></div></section><FinalCTA /></main>; }
