import { Router } from 'express';
import mongoose from 'mongoose';
import { PlatformAdminAuthenticatedRequest } from '../auth/middleware';
import { AIUsage } from '../models/AIUsage';
import { BillingTransaction } from '../models/BillingTransaction';
import { Business } from '../models/Business';
import { BusinessChannel } from '../models/BusinessChannel';
import { BusinessMember } from '../models/BusinessMember';
import { Conversation } from '../models/Conversation';
import { CourierIntegration } from '../models/CourierIntegration';
import { Customer } from '../models/Customer';
import { ErrorLog } from '../models/ErrorLog';
import { Knowledge } from '../models/Knowledge';
import { MerchantActivity } from '../models/MerchantActivity';
import { Order } from '../models/Order';
import { PlatformAuditLog } from '../models/PlatformAuditLog';
import { Product } from '../models/Product';
import { Subscription, SubscriptionStatus } from '../models/Subscription';
import { SubscriptionEvent, SubscriptionEventType } from '../models/SubscriptionEvent';
import { TrainingSource } from '../models/TrainingSource';
import { User } from '../models/User';
import { getHealthStatus } from '../services/health.service';
import { writePlatformAudit } from '../services/platform-audit.service';

const router=Router();
const safeRegex=(value:unknown)=>new RegExp(String(value||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&').slice(0,80),'i');
const objectId=(value:unknown)=>mongoose.isValidObjectId(String(value))?new mongoose.Types.ObjectId(String(value)):null;
const reason=(value:unknown)=>String(value||'').trim().slice(0,500);
const pageOf=(req:any)=>({page:Math.max(1,Number(req.query.page)||1),limit:Math.min(100,Math.max(1,Number(req.query.limit)||20))});
const monthStart=(date=new Date())=>new Date(date.getFullYear(),date.getMonth(),1);
const previousMonthStart=(date=new Date())=>new Date(date.getFullYear(),date.getMonth()-1,1);
const dayStart=(date=new Date())=>new Date(date.getFullYear(),date.getMonth(),date.getDate());
function range(value:unknown){const now=new Date();const name=String(value||'30d');let from:Date;if(name==='today')from=dayStart(now);else if(name==='7d')from=new Date(now.getTime()-7*86400000);else if(name==='this_month')from=monthStart(now);else if(name==='previous_month'){from=previousMonthStart(now);return {name,from,to:monthStart(now)}}else {const months:{[key:string]:number}={ '3m':3,'6m':6,'12m':12 };from=months[name]?new Date(now.getFullYear(),now.getMonth()-months[name]+1,1):new Date(now.getTime()-30*86400000)}return {name,from,to:now}}
const paidMatch=(from?:Date,to?:Date)=>({status:'PAID',paidAt:{...(from?{$gte:from}:{}),...(to?{$lt:to}:{})}});
const revenueStages=(match:Record<string,unknown>)=>[{$match:match},{$group:{_id:null,revenue:{$sum:{$cond:[{$eq:['$type','REFUND']},{$multiply:['$amount',-1]},'$amount']}},refunds:{$sum:{$cond:[{$eq:['$type','REFUND']},'$amount',0]}},newRevenue:{$sum:{$cond:[{$eq:['$type','NEW_SUBSCRIPTION']},'$amount',0]}},renewalRevenue:{$sum:{$cond:[{$eq:['$type','RENEWAL']},'$amount',0]}}}}];

router.get('/me',(req:PlatformAdminAuthenticatedRequest,res)=>res.json(req.platformAdmin));

router.get('/overview',async(req,res)=>{
 const selected=range(req.query.period);const now=new Date();const today=dayStart(now);const thisMonth=monthStart(now);const previousMonth=previousMonthStart(now);const activeNow=new Date(now.getTime()-5*60000);
 const [businesses,newBusinesses,users,subscriptionGroups,newSubscriptions,renewals,currentRevenue,previousRevenue,totalRevenue,mrr,aiToday,aiMonth,aiPrevious,aiTotal,activeNowRows,activeTodayRows,activeMonthRows,activeBusinessesToday,activeBusinessesMonth,growth,revenueTrend,usageTrend]=await Promise.all([
  Business.collection.countDocuments({}),Business.collection.countDocuments({createdAt:{$gte:thisMonth}}),User.collection.countDocuments({}),Subscription.collection.aggregate([{$group:{_id:'$status',count:{$sum:1}}}]).toArray(),BillingTransaction.collection.countDocuments({...paidMatch(thisMonth),'type':'NEW_SUBSCRIPTION'}),BillingTransaction.collection.countDocuments({...paidMatch(thisMonth),'type':'RENEWAL'}),BillingTransaction.collection.aggregate(revenueStages(paidMatch(thisMonth)) as any).toArray(),BillingTransaction.collection.aggregate(revenueStages(paidMatch(previousMonth,thisMonth)) as any).toArray(),BillingTransaction.collection.aggregate(revenueStages({status:'PAID'}) as any).toArray(),Subscription.collection.aggregate([{$match:{status:'ACTIVE'}},{$group:{_id:null,value:{$sum:{$switch:{branches:[{case:{$eq:['$billingPeriod','monthly']},then:'$price'},{case:{$eq:['$billingPeriod','annual']},then:{$divide:['$price',12]}}],default:0}}}}}]).toArray(),
  usageSummary(today),usageSummary(thisMonth),usageSummary(previousMonth,thisMonth),usageSummary(),MerchantActivity.collection.distinct('userId',{lastSeenAt:{$gte:activeNow}}),MerchantActivity.collection.distinct('userId',{lastSeenAt:{$gte:today}}),MerchantActivity.collection.distinct('userId',{lastSeenAt:{$gte:thisMonth}}),MerchantActivity.collection.distinct('businessId',{lastSeenAt:{$gte:today}}),MerchantActivity.collection.distinct('businessId',{lastSeenAt:{$gte:thisMonth}}),
  Business.collection.aggregate([{$match:{createdAt:{$gte:selected.from,$lt:selected.to}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$createdAt'}},value:{$sum:1}}},{$sort:{_id:1}}]).toArray(),BillingTransaction.collection.aggregate([{$match:paidMatch(selected.from,selected.to)},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$paidAt'}},value:{$sum:{$cond:[{$eq:['$type','REFUND']},{$multiply:['$amount',-1]},'$amount']}}}},{$sort:{_id:1}}]).toArray(),AIUsage.collection.aggregate([{$match:{createdAt:{$gte:selected.from,$lt:selected.to}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$createdAt'}},requests:{$sum:1},tokens:{$sum:{$ifNull:['$totalTokens',0]}},knownCost:{$sum:{$ifNull:['$estimatedCost',0]}},unknownCost:{$sum:{$cond:[{$eq:['$estimatedCost',null]},1,0]}}}},{$sort:{_id:1}}]).toArray()
 ]);
 const subscriptions=Object.fromEntries(subscriptionGroups.map((row:any)=>[row._id,row.count]));const aiStates=await Business.collection.aggregate([{$group:{_id:{$ifNull:['$aiAccess.status','ENABLED']},count:{$sum:1}}}]).toArray();
 res.json({period:selected,businesses:{total:businesses,newThisMonth:newBusinesses,active:await Business.collection.countDocuments({status:'active'}),suspended:await Business.collection.countDocuments({status:'suspended'})},users:{total:users,activeNow:activeNowRows.length,activeToday:activeTodayRows.length,activeThisMonth:activeMonthRows.length},activeBusinesses:{today:activeBusinessesToday.length,thisMonth:activeBusinessesMonth.length},subscriptions:{...subscriptions,newThisMonth:newSubscriptions,renewalsThisMonth:renewals},revenue:{today:(await BillingTransaction.collection.aggregate(revenueStages(paidMatch(today)) as any).toArray())[0]||{},thisMonth:currentRevenue[0]||{},previousMonth:previousRevenue[0]||{},total:totalRevenue[0]||{},mrr:mrr[0]?.value||0},ai:{states:Object.fromEntries(aiStates.map((row:any)=>[row._id,row.count])),today:aiToday,month:aiMonth,previousMonth:aiPrevious,total:aiTotal},trends:{businessGrowth:growth,revenue:revenueTrend,aiUsage:usageTrend}});
});

async function usageSummary(from?:Date,to?:Date){const match:any={};if(from||to)match.createdAt={...(from?{$gte:from}:{}),...(to?{$lt:to}:{})};const rows=await AIUsage.collection.aggregate([{$match:match},{$group:{_id:null,requests:{$sum:1},inputTokens:{$sum:{$ifNull:['$inputTokens',0]}},outputTokens:{$sum:{$ifNull:['$outputTokens',0]}},totalTokens:{$sum:{$ifNull:['$totalTokens',0]}},knownEstimatedCost:{$sum:{$ifNull:['$estimatedCost',0]}},unknownCostRequests:{$sum:{$cond:[{$eq:['$estimatedCost',null]},1,0]}}}}]).toArray();const row=rows[0]||{requests:0,inputTokens:0,outputTokens:0,totalTokens:0,knownEstimatedCost:0,unknownCostRequests:0};return {...row,estimatedCost:row.unknownCostRequests?null:row.knownEstimatedCost}}

router.get('/businesses',async(req,res)=>{const {page,limit}=pageOf(req);const search=req.query.search?safeRegex(req.query.search):null;const filter=String(req.query.filter||'');const month=monthStart();const pipeline:any[]=[
 {$lookup:{from:BusinessMember.collection.name,let:{bid:'$_id'},pipeline:[{$match:{$expr:{$eq:['$businessId','$$bid']}}},{$lookup:{from:User.collection.name,localField:'userId',foreignField:'_id',as:'user'}},{$project:{role:1,status:1,user:{$arrayElemAt:['$user',0]}}}],as:'members'}},
 {$lookup:{from:Subscription.collection.name,localField:'_id',foreignField:'businessId',as:'subscriptions'}},{$lookup:{from:AIUsage.collection.name,let:{bid:'$_id'},pipeline:[{$match:{$expr:{$and:[{$eq:['$businessId','$$bid']},{$gte:['$createdAt',month]}]}}},{$group:{_id:null,requests:{$sum:1},tokens:{$sum:{$ifNull:['$totalTokens',0]}},cost:{$sum:{$ifNull:['$estimatedCost',0]}},unknown:{$sum:{$cond:[{$eq:['$estimatedCost',null]},1,0]}}}}],as:'usage'}},
 {$lookup:{from:BillingTransaction.collection.name,let:{bid:'$_id'},pipeline:[{$match:{$expr:{$and:[{$eq:['$businessId','$$bid']},{$eq:['$status','PAID']}]}}},{$group:{_id:null,revenue:{$sum:{$cond:[{$eq:['$type','REFUND']},{$multiply:['$amount',-1]},'$amount']}}}}],as:'billing'}},{$lookup:{from:MerchantActivity.collection.name,let:{bid:'$_id'},pipeline:[{$match:{$expr:{$eq:['$businessId','$$bid']}}},{$sort:{lastSeenAt:-1}},{$limit:1}],as:'activity'}},{$lookup:{from:BusinessChannel.collection.name,localField:'_id',foreignField:'businessId',as:'channels'}},{$lookup:{from:CourierIntegration.collection.name,localField:'_id',foreignField:'businessId',as:'couriers'}},
 {$addFields:{subscription:{$arrayElemAt:['$subscriptions',0]},usage:{$ifNull:[{$arrayElemAt:['$usage',0]},{requests:0,tokens:0,cost:0,unknown:0}]},revenue:{$ifNull:[{$arrayElemAt:['$billing.revenue',0]},0]},lastActive:{$arrayElemAt:['$activity.lastSeenAt',0]},owner:{$arrayElemAt:[{$filter:{input:'$members',as:'member',cond:{$eq:['$$member.role','Owner']}}},0]}}}
 ];const matches:any[]=[];if(search)matches.push({$or:[{name:search},{slug:search},{'owner.user.email':search},{'subscription.plan':search}]});if(filter==='active'||filter==='suspended')matches.push({status:filter});if(filter==='ai_active')matches.push({'aiAccess.status':{$in:[null,'ENABLED']}});if(filter==='ai_suspended')matches.push({'aiAccess.status':{$ne:'ENABLED'}});if(['TRIAL','ACTIVE','PAST_DUE','EXPIRED','CANCELLED'].includes(filter.toUpperCase()))matches.push({'subscription.status':filter.toUpperCase()});if(filter==='recent')matches.push({createdAt:{$gte:new Date(Date.now()-30*86400000)}});if(filter==='inactive')matches.push({$or:[{lastActive:{$lt:new Date(Date.now()-30*86400000)}},{lastActive:null}]});if(matches.length)pipeline.push({$match:{$and:matches}});pipeline.push({$sort:{createdAt:-1}},{$facet:{data:[{$skip:(page-1)*limit},{$limit:limit},{$project:{name:1,slug:1,status:1,businessType:1,createdAt:1,aiAccess:1,owner:{name:'$owner.user.name',email:'$owner.user.email'},merchantUsers:{$size:'$members'},subscription:1,usage:1,revenue:1,lastActive:1,integrations:{website:{$size:{$filter:{input:'$channels',as:'c',cond:{$eq:['$$c.platform','web']}}}},facebook:{$size:{$filter:{input:'$channels',as:'c',cond:{$eq:['$$c.platform','facebook']}}}},courier:{$size:'$couriers'}}}}],total:[{$count:'count'}]}});const [result]=await Business.collection.aggregate(pipeline).toArray();const total=result.total[0]?.count||0;res.json({data:result.data,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}})});

router.get('/businesses/:id',async(req,res)=>{
 const id=objectId(req.params.id);if(!id)return res.status(400).json({error:'Valid business is required'});
 const business=await Business.collection.findOne({_id:id},{projection:{brandVoice:0}});if(!business)return res.status(404).json({error:'Business not found'});
 const memberPipeline:any[]=[{$match:{businessId:id}},{$lookup:{from:User.collection.name,localField:'userId',foreignField:'_id',as:'user'}},{$project:{role:1,status:1,user:{$let:{vars:{u:{$arrayElemAt:['$user',0]}},in:{id:'$$u._id',name:'$$u.name',email:'$$u.email',status:'$$u.status',lastSeenAt:'$$u.lastSeenAt'}}}}}];
 const [members,subscription,history,billing,usage,products,knowledge,customers,orders,conversations,channels,couriers,training,lastActivity]=await Promise.all([
  BusinessMember.collection.aggregate(memberPipeline).toArray(),Subscription.collection.findOne({businessId:id}),SubscriptionEvent.collection.find({businessId:id}).sort({createdAt:-1}).limit(100).toArray(),BillingTransaction.collection.aggregate(revenueStages({businessId:id,status:'PAID'}) as any).toArray(),AIUsage.collection.aggregate([{$match:{businessId:id}},{$group:{_id:null,requests:{$sum:1},tokens:{$sum:{$ifNull:['$totalTokens',0]}},knownCost:{$sum:{$ifNull:['$estimatedCost',0]}},unknown:{$sum:{$cond:[{$eq:['$estimatedCost',null]},1,0]}}}}]).toArray(),Product.collection.countDocuments({businessId:id,isActive:true}),Knowledge.collection.countDocuments({businessId:id,status:'active'}),Customer.collection.countDocuments({businessId:id}),Order.collection.countDocuments({businessId:id}),Conversation.collection.countDocuments({businessId:id}),BusinessChannel.collection.find({businessId:id},{projection:{platform:1,name:1,status:1,updatedAt:1}}).toArray(),CourierIntegration.collection.find({businessId:id},{projection:{provider:1,status:1,lastTestedAt:1,lastErrorCode:1,updatedAt:1}}).toArray(),TrainingSource.collection.find({businessId:id},{projection:{type:1,name:1,status:1,lastSyncedAt:1,errorCode:1,stats:1}}).toArray(),MerchantActivity.collection.find({businessId:id}).sort({lastSeenAt:-1}).limit(1).next()
 ]);
 res.json({business,members,subscription,subscriptionHistory:history,revenue:billing[0]||{},aiUsage:usage[0]||{requests:0,tokens:0,knownCost:0,unknown:0},counts:{products,knowledge,customers,orders,conversations},integrations:{channels,couriers,training},lastActivity:lastActivity?.lastSeenAt});
});

router.patch('/businesses/:id/status',async(req:PlatformAdminAuthenticatedRequest,res)=>{const id=objectId(req.params.id);const next=String(req.body?.status);const why=reason(req.body?.reason);if(!id||!['active','suspended'].includes(next)||!why)return res.status(400).json({error:'Valid business, status, and reason are required'});const previous=await Business.collection.findOne({_id:id},{projection:{name:1,status:1}});if(!previous)return res.status(404).json({error:'Business not found'});await Business.collection.updateOne({_id:id},{$set:{status:next,updatedAt:new Date()}});await writePlatformAudit({platformAdminId:req.platformAdmin!.id,action:next==='suspended'?'BUSINESS_SUSPENDED':'BUSINESS_REACTIVATED',targetType:'business',targetId:id.toString(),businessId:id.toString(),previousValue:{status:previous.status},newValue:{status:next},reason:why});res.json({...previous,status:next})});
router.patch('/businesses/:id/ai-access',async(req:PlatformAdminAuthenticatedRequest,res)=>{const id=objectId(req.params.id);const next=String(req.body?.status);const why=reason(req.body?.reason);if(!id||!['ENABLED','SUSPENDED_BY_PLATFORM'].includes(next)||!why)return res.status(400).json({error:'Valid AI status and reason are required'});const previous=await Business.collection.findOne({_id:id},{projection:{name:1,aiAccess:1}});if(!previous)return res.status(404).json({error:'Business not found'});const value={status:next,reason:why,changedAt:new Date(),changedBy:req.platformAdmin!.id};await Business.collection.updateOne({_id:id},{$set:{aiAccess:value,updatedAt:new Date()}});await writePlatformAudit({platformAdminId:req.platformAdmin!.id,action:next==='ENABLED'?'AI_RESUMED':'AI_SUSPENDED',targetType:'business_ai',targetId:id.toString(),businessId:id.toString(),previousValue:previous.aiAccess,newValue:value,reason:why});res.json({businessId:id,aiAccess:value})});

router.get('/subscriptions',async(req,res)=>{const {page,limit}=pageOf(req);const match:any={};if(req.query.status)match.status=String(req.query.status);const pipeline:any[]=[{$match:match},{$lookup:{from:Business.collection.name,localField:'businessId',foreignField:'_id',as:'business'}},{$addFields:{business:{$arrayElemAt:['$business',0]}}}];if(req.query.search)pipeline.push({$match:{$or:[{plan:safeRegex(req.query.search)},{'business.name':safeRegex(req.query.search)}]}});pipeline.push({$sort:{updatedAt:-1}},{$facet:{data:[{$skip:(page-1)*limit},{$limit:limit},{$project:{businessId:1,plan:1,status:1,billingPeriod:1,price:1,currency:1,startedAt:1,currentPeriodStart:1,currentPeriodEnd:1,trialEndsAt:1,cancelledAt:1,renewedAt:1,createdAt:1,updatedAt:1,'business.name':1}}],total:[{$count:'count'}]}});const [result]=await Subscription.collection.aggregate(pipeline).toArray();const total=result.total[0]?.count||0;res.json({data:result.data,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}})});
router.put('/businesses/:id/subscription',async(req:PlatformAdminAuthenticatedRequest,res)=>{const id=objectId(req.params.id);const why=reason(req.body?.reason);const status=String(req.body?.status) as SubscriptionStatus;const plan=String(req.body?.plan||'').trim();const billingPeriod=String(req.body?.billingPeriod);const price=Number(req.body?.price);const eventType=String(req.body?.eventType||'STATUS_CHANGE') as SubscriptionEventType;if(!id||!why||!plan||!['TRIAL','ACTIVE','PAST_DUE','EXPIRED','CANCELLED','SUSPENDED'].includes(status)||!['monthly','annual','custom'].includes(billingPeriod)||!Number.isFinite(price)||price<0||!['START','NEW_SUBSCRIPTION','RENEWAL','UPGRADE','DOWNGRADE','EXPIRY','CANCELLATION','REACTIVATION','STATUS_CHANGE'].includes(eventType))return res.status(400).json({error:'Valid subscription fields and reason are required'});if(!await Business.collection.findOne({_id:id}))return res.status(404).json({error:'Business not found'});const previous=await Subscription.collection.findOne({businessId:id});const dates=['startedAt','currentPeriodStart','currentPeriodEnd','trialEndsAt','cancelledAt','renewedAt'];const values:any={businessId:id,plan,status,billingPeriod,price,currency:String(req.body?.currency||'BDT').slice(0,8)};for(const key of dates)if(req.body?.[key])values[key]=new Date(req.body[key]);if(!values.startedAt)values.startedAt=previous?.startedAt||new Date();const subscription=await Subscription.collection.findOneAndUpdate({businessId:id},{$set:values,$setOnInsert:{createdAt:new Date()},$currentDate:{updatedAt:true}},{upsert:true,returnDocument:'after'});await SubscriptionEvent.create({businessId:id,subscriptionId:subscription!._id,type:eventType,previousValue:previous?{plan:previous.plan,status:previous.status,billingPeriod:previous.billingPeriod,price:previous.price}:null,newValue:values,reason:why,platformAdminId:req.platformAdmin!.id});if(['PAST_DUE','EXPIRED','CANCELLED','SUSPENDED'].includes(status))await Business.collection.updateOne({_id:id,'aiAccess.status':{$nin:['SUSPENDED_BY_PLATFORM','DISABLED_BY_MERCHANT']}},{$set:{'aiAccess.status':'SUSPENDED_BY_SUBSCRIPTION','aiAccess.reason':`Subscription ${status}`,'aiAccess.changedAt':new Date(),'aiAccess.changedBy':req.platformAdmin!.id}});else await Business.collection.updateOne({_id:id,'aiAccess.status':'SUSPENDED_BY_SUBSCRIPTION'},{$set:{'aiAccess.status':'ENABLED','aiAccess.reason':'Subscription entitlement restored','aiAccess.changedAt':new Date(),'aiAccess.changedBy':req.platformAdmin!.id}});await writePlatformAudit({platformAdminId:req.platformAdmin!.id,action:eventType,targetType:'subscription',targetId:subscription!._id.toString(),businessId:id.toString(),previousValue:previous,newValue:values,reason:why});res.json(subscription)});

router.get('/revenue',async(req,res)=>{const selected=range(req.query.period);const {page,limit}=pageOf(req);const match:any={};if(req.query.search){const businesses=await Business.collection.find({name:safeRegex(req.query.search)},{projection:{_id:1}}).toArray();match.$or=[{businessId:{$in:businesses.map(b=>b._id)}},{providerReference:safeRegex(req.query.search)}]};const [summary,byPlan,trend,data,total]=await Promise.all([BillingTransaction.collection.aggregate(revenueStages({status:'PAID',paidAt:{$gte:selected.from,$lt:selected.to}}) as any).toArray(),BillingTransaction.collection.aggregate([{$match:{status:'PAID',paidAt:{$gte:selected.from,$lt:selected.to}}},{$lookup:{from:Subscription.collection.name,localField:'subscriptionId',foreignField:'_id',as:'subscription'}},{$group:{_id:{$ifNull:[{$arrayElemAt:['$subscription.plan',0]},'Unassigned']},value:{$sum:{$cond:[{$eq:['$type','REFUND']},{$multiply:['$amount',-1]},'$amount']}}}},{$sort:{value:-1}}]).toArray(),BillingTransaction.collection.aggregate([{$match:{status:'PAID',paidAt:{$gte:selected.from,$lt:selected.to}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$paidAt'}},value:{$sum:{$cond:[{$eq:['$type','REFUND']},{$multiply:['$amount',-1]},'$amount']}}}},{$sort:{_id:1}}]).toArray(),BillingTransaction.collection.aggregate([{$match:match},{$sort:{createdAt:-1}},{$skip:(page-1)*limit},{$limit:limit},{$lookup:{from:Business.collection.name,localField:'businessId',foreignField:'_id',as:'business'}},{$project:{type:1,amount:1,currency:1,status:1,paymentMethod:1,provider:1,providerReference:1,paidAt:1,createdAt:1,isTest:1,businessName:{$arrayElemAt:['$business.name',0]}}}]).toArray(),BillingTransaction.collection.countDocuments(match)]);res.json({period:selected,summary:summary[0]||{},byPlan,trend,data,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}})});
router.post('/billing/adjustments',async(req:PlatformAdminAuthenticatedRequest,res)=>{const businessId=objectId(String(req.body?.businessId||''));const why=reason(req.body?.reason);const amount=Number(req.body?.amount);const type=String(req.body?.type);if(!businessId||!why||!Number.isFinite(amount)||amount<0||!['ADJUSTMENT','REFUND'].includes(type))return res.status(400).json({error:'Business, non-negative amount, adjustment type, and reason are required'});const transaction=await BillingTransaction.create({businessId,type,amount,currency:String(req.body?.currency||'BDT').slice(0,8),status:'PAID',paymentMethod:'manual',provider:'manual',providerReference:String(req.body?.providerReference||'').trim()||undefined,reason:why,isTest:Boolean(req.body?.isTest),createdBy:req.platformAdmin!.id,paidAt:new Date()});await writePlatformAudit({platformAdminId:req.platformAdmin!.id,action:'MANUAL_BILLING_ADJUSTMENT',targetType:'billing_transaction',targetId:transaction._id.toString(),businessId:businessId.toString(),previousValue:null,newValue:{type,amount,currency:transaction.currency,status:'PAID',isTest:transaction.isTest},reason:why});res.status(201).json(transaction)});

router.get('/usage',async(req,res)=>{const selected=range(req.query.period);const data=await AIUsage.collection.aggregate([{$match:{createdAt:{$gte:selected.from,$lt:selected.to}}},{$group:{_id:{businessId:'$businessId',provider:{$ifNull:['$provider','unknown']},model:'$model'},requests:{$sum:1},inputTokens:{$sum:{$ifNull:['$inputTokens',0]}},outputTokens:{$sum:{$ifNull:['$outputTokens',0]}},totalTokens:{$sum:{$ifNull:['$totalTokens',0]}},knownCost:{$sum:{$ifNull:['$estimatedCost',0]}},unknownCostRequests:{$sum:{$cond:[{$eq:['$estimatedCost',null]},1,0]}}}},{$lookup:{from:Business.collection.name,localField:'_id.businessId',foreignField:'_id',as:'business'}},{$project:{businessId:'$_id.businessId',provider:'$_id.provider',model:'$_id.model',businessName:{$ifNull:[{$arrayElemAt:['$business.name',0]},'Deleted business']},requests:1,inputTokens:1,outputTokens:1,totalTokens:1,knownCost:1,unknownCostRequests:1,estimatedCost:{$cond:[{$gt:['$unknownCostRequests',0]},null,'$knownCost']} }},{$sort:{knownCost:-1}}]).toArray();res.json({period:selected,total:await usageSummary(selected.from,selected.to),data})});

router.get('/users',async(req,res)=>{const {page,limit}=pageOf(req);const match=req.query.search?{$or:[{name:safeRegex(req.query.search)},{email:safeRegex(req.query.search)}]}:{};const [data,total]=await Promise.all([User.collection.aggregate([{$match:match},{$sort:{createdAt:-1}},{$skip:(page-1)*limit},{$limit:limit},{$lookup:{from:BusinessMember.collection.name,localField:'_id',foreignField:'userId',pipeline:[{$lookup:{from:Business.collection.name,localField:'businessId',foreignField:'_id',as:'business'}},{$project:{role:1,status:1,business:{$arrayElemAt:['$business',0]}}}],as:'memberships'}},{$project:{name:1,email:1,emailVerified:1,status:1,lastSeenAt:1,createdAt:1,'memberships.role':1,'memberships.status':1,'memberships.business._id':1,'memberships.business.name':1}}]).toArray(),User.collection.countDocuments(match)]);res.json({data,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}})});
router.patch('/users/:id/status',async(req:PlatformAdminAuthenticatedRequest,res)=>{const id=objectId(req.params.id);const status=String(req.body?.status);const why=reason(req.body?.reason);if(!id||!['active','disabled'].includes(status)||!why)return res.status(400).json({error:'Valid user status and reason are required'});const previous=await User.collection.findOne({_id:id},{projection:{name:1,email:1,status:1}});if(!previous)return res.status(404).json({error:'User not found'});await User.collection.updateOne({_id:id},{$set:{status,updatedAt:new Date()}});await writePlatformAudit({platformAdminId:req.platformAdmin!.id,action:status==='disabled'?'USER_SUSPENDED':'USER_REACTIVATED',targetType:'user',targetId:id.toString(),previousValue:{status:previous.status},newValue:{status},reason:why});res.json({...previous,status})});

router.get('/integrations',async(_req,res)=>{const [channels,couriers,training,businesses]=await Promise.all([BusinessChannel.collection.aggregate([{$group:{_id:{platform:'$platform',status:'$status'},count:{$sum:1}}}]).toArray(),CourierIntegration.collection.aggregate([{$group:{_id:{provider:'$provider',status:'$status'},count:{$sum:1}}}]).toArray(),TrainingSource.collection.aggregate([{$group:{_id:{type:'$type',status:'$status'},count:{$sum:1},lastSuccessful:{$max:'$lastSyncedAt'},failedScans:{$sum:{$ifNull:['$stats.failed',0]}},products:{$sum:{$ifNull:['$stats.products',0]}},knowledge:{$sum:{$ifNull:['$stats.knowledge',0]}},needsReview:{$sum:{$ifNull:['$stats.needsAttention',0]}}}}]).toArray(),Business.collection.countDocuments({})]);res.json({channels,couriers,training,businesses,aiProviderConfigured:Boolean(process.env.GROQ_API_KEY||process.env.OPENAI_API_KEY),storageConfigured:Boolean(process.env.CLOUDINARY_URL||process.env.CLOUDINARY_CLOUD_NAME)})});
router.get('/audit',async(req,res)=>{const {page,limit}=pageOf(req);const match:any={};if(req.query.action)match.action=String(req.query.action);if(req.query.businessId&&objectId(String(req.query.businessId)))match.businessId=objectId(String(req.query.businessId));if(req.query.search)match.$or=[{action:safeRegex(req.query.search)},{targetId:safeRegex(req.query.search)},{reason:safeRegex(req.query.search)}];const [data,total]=await Promise.all([PlatformAuditLog.collection.aggregate([{$match:match},{$sort:{createdAt:-1}},{$skip:(page-1)*limit},{$limit:limit},{$lookup:{from:'platformadmins',localField:'platformAdminId',foreignField:'_id',as:'admin'}},{$lookup:{from:Business.collection.name,localField:'businessId',foreignField:'_id',as:'business'}},{$project:{action:1,targetType:1,targetId:1,previousValue:1,newValue:1,reason:1,createdAt:1,admin:{$let:{vars:{a:{$arrayElemAt:['$admin',0]}},in:{id:'$$a._id',name:'$$a.name',email:'$$a.email'}}},business:{$let:{vars:{b:{$arrayElemAt:['$business',0]}},in:{id:'$$b._id',name:'$$b.name'}}}}}]).toArray(),PlatformAuditLog.collection.countDocuments(match)]);res.json({data,pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}})});
router.get('/errors',async(_req,res)=>{const errors=await ErrorLog.collection.find({},{projection:{type:1,message:1,timestamp:1}}).sort({timestamp:-1}).limit(100).toArray();res.json(errors.map(error=>({...error,message:String(error.message||'').slice(0,1000).replace(/Bearer\s+[A-Za-z0-9._~-]+/gi,'Bearer [redacted]').replace(/\bsk-[A-Za-z0-9_-]{12,}\b/g,'[redacted key]').replace(/(secret|token|password|api[_ -]?key)\s*[=:]\s*[^\s,;]+/gi,'$1=[redacted]')})))});
router.get('/health',async(_req,res)=>{const [facebookChannels,steadfastConnections]=await Promise.all([BusinessChannel.collection.countDocuments({platform:'facebook',status:'active'}),CourierIntegration.collection.countDocuments({provider:'steadfast',status:'connected'})]);res.json({...await getHealthStatus(),facebookChannels,steadfastConnections,storage:process.env.CLOUDINARY_URL||process.env.CLOUDINARY_CLOUD_NAME?'configured':'not_configured'})});

export default router;
